/***************************************************************************
 *   MatCrossBible  (old name: CrossBgBible)                               *
 *   Copyright (C) 2007-2020 by MatCraft, Bulgaria                         *
 *   matcraft.org@gmail.com                                                *
 *   https://www.matcraft.org/  (old site: https://www.crossbgbible.com/)  *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 ***************************************************************************/

#include "trstrings.h"

TrStrings::TrStrings() 
{
  trPath = QString("%1/Tr").arg(QCoreApplication::applicationDirPath());

  // Генерира ReadMe.txt файл (ако няма такъв):
  createNewReadMeFile();

  // Генерира Bulgarian.tr и English.tr файл (ако няма такива):
  if (!QFile::exists(QString("%1/Bulgarian.tr").arg(trPath))) // Ако няма такъв файл.
  {
    isBulgarianAppTranslation = true;
    currentAppTranslation = QString("Bulgarian");
    strSettings = new QSettings(QString("%1/%2.tr").arg(trPath).arg(currentAppTranslation), QSettings::IniFormat, this);
    strSettings->setIniCodec(QTextCodec::codecForName("UTF-8"));
    strSettings->setValue(QString("APP_LAYOUT_DIRECTION"), QString("LeftToRight")); // LeftToRight RightToLeft
    strSettings->setValue(QString("LANGUAGE"), QString("Bulgarian")); // Език.
    strSettings->setValue(QString("TRANSLATOR"), QString("Generated by MatCrossBible")); // Преводач.
    strSettings->setValue(QString("LAST_MODIFY_DATE"), QDate::currentDate().toString("yyyy.MM.dd")); // Последна дата на промяна (например 2017.03.24).
    initializeStrings();
    delete strSettings;
  }
  if (!QFile::exists(QString("%1/English.tr").arg(trPath))) // Ако няма такъв файл.
  {
    isBulgarianAppTranslation = false;
    currentAppTranslation = QString("English");
    strSettings = new QSettings(QString("%1/%2.tr").arg(trPath).arg(currentAppTranslation), QSettings::IniFormat, this);
    strSettings->setIniCodec(QTextCodec::codecForName("UTF-8"));
    strSettings->setValue(QString("APP_LAYOUT_DIRECTION"), QString("LeftToRight")); // LeftToRight RightToLeft
    strSettings->setValue(QString("LANGUAGE"), QString("English")); // Език.
    strSettings->setValue(QString("TRANSLATOR"), QString("Generated by MatCrossBible")); // Преводач.
    strSettings->setValue(QString("LAST_MODIFY_DATE"), QDate::currentDate().toString("yyyy.MM.dd")); // Последна дата на промяна (например 2017.03.24).
    initializeStrings();
    delete strSettings;
  }

  // Определя текущия език на интерфейса, избран при последното пускане на програмата:
  QSettings currSettings(QString("%1/CurrentAppTranslation.ini").arg(trPath), QSettings::IniFormat, this);
  currSettings.setIniCodec(QTextCodec::codecForName("UTF-8"));
  currentAppTranslation = currSettings.value(QString("CurrentAppTranslation"), QString("")).toString();

  // Създава списък с всички налични tr файлове:
  setAllAppTranslation();

  // Проверява дали текущия избран език е един от горните реално съществуващи езици (файлове):
  if (!allAppTranslation.contains(currentAppTranslation)) // Ако още не е направен избор на език или последно избрания език вече не съществува като реален файл.
  {
    // Ако има проблем с избора на език, тук се прави повторен и окончателен автоматичен избор (би могло да се направи тук да излиза форма с комбобокс и потребителят да избере езика, но е излишно сложно това):
    QLocale local; // Взима системния локал (държава, език...).
    QString language = QLocale::languageToString(local.language()); // Името на езика на системния локал (не езика на операционната система).

    if (allAppTranslation.contains(language)) // Ако езика на системния локал съвпада с името на съществуващ tr файл.
    {
      currentAppTranslation = language; // Избира съответния език и ако файлът е празен или ако има празни стрингове, ще ги възстанови, на български ако локал-а е Bulgarian или на английски за останалите локал-и.
    }
    else // Ако няма съвпадение с езика на системния локал.
    {
      currentAppTranslation = allAppTranslation[0]; // Избира първия от списъка (в който има поне два езика и английският е преди българския) и ако файлът е празен или ако има празни стрингове, ще ги възстанови, на английски (или на български).
    }

    currSettings.setValue(QString("CurrentAppTranslation"), currentAppTranslation);
  }

  isBulgarianAppTranslation = (currentAppTranslation.toLower() == QString("bulgarian"));

  // Инициализира стринговете:
  strSettings = new QSettings(QString("%1/%2.tr").arg(trPath).arg(currentAppTranslation), QSettings::IniFormat, this);
  strSettings->setIniCodec(QTextCodec::codecForName("UTF-8"));
  initializeStrings();
  delete strSettings;

  // Създава списък с всички вградени езици на имената на книгите:
  allBooksTranslation << QString("Bulgarian");
  allBooksTranslation << QString("Czech");
  allBooksTranslation << QString("English");
  allBooksTranslation << QString("French");
  allBooksTranslation << QString("German");
  allBooksTranslation << QString("Hungarian");
  allBooksTranslation << QString("Italian");
  allBooksTranslation << QString("Polish");
  allBooksTranslation << QString("Romanian");
  allBooksTranslation << QString("Russian");
  allBooksTranslation << QString("Spanish");
}

void TrStrings::initEmbedBooksNames(QString language)
{
  if (language.isEmpty())
    return;
  else if (language == "Bulgarian")
    initBooksBulgarian();
  else if (language == "Czech")
    initBooksCzech();
  else if (language == "English")
    initBooksEnglish();
  else if (language == "French")
    initBooksFrench();
  else if (language == "German")
    initBooksGerman();
  else if (language == "Hungarian")
    initBooksHungarian();
  else if (language == "Italian")
    initBooksItalian();
  else if (language == "Polish")
    initBooksPolish();
  else if (language == "Romanian")
    initBooksRomanian();
  else if (language == "Russian")
    initBooksRussian();
  else if (language == "Spanish")
    initBooksSpanish();
  // Ако няма такъв език ще останат тези от TR файла.
}

void TrStrings::setAllAppTranslation()
{
  allAppTranslation.clear();
  allAppTranslation << QString("*.tr"); // Тук се използва временно за други цели (филтър).
  QDir dir(trPath);
  dir.setSorting(QDir::Name);
  dir.setNameFilters(allAppTranslation);
  allAppTranslation = dir.entryList(); // Тук е по предназначение и съдържа имената на всички файлове с разширение .tr (по-долу разширението ще бъде изтрито).

  // Премахва разширенията на имената на файловете (защото ще се показват в комбобокс):
  for (int i = 0; i < allAppTranslation.count(); i++)
  {
    allAppTranslation[i].remove(QString(".tr")); // Изтрива .tr от името на файла.
  }

  // Ако поради някаква причина двата файла (българския и английския) не са създадени, добавя имената им в списъка, защото стринговете ще се заредят от тук, а не от файловете:
  if (!allAppTranslation.contains(QString("English"))) allAppTranslation << QString("English"); // Първо се добавя английският за да е с предимство.
  if (!allAppTranslation.contains(QString("Bulgarian"))) allAppTranslation << QString("Bulgarian");
}

void TrStrings::saveCurrentAppTranslationToSettings()
{
  QSettings currSettings(QString("%1/CurrentAppTranslation.ini").arg(trPath), QSettings::IniFormat, this);
  currSettings.setIniCodec(QTextCodec::codecForName("UTF-8"));
  currSettings.setValue(QString("CurrentAppTranslation"), currentAppTranslation);
}

void TrStrings::setBooksStr()
{
  if (isBulgarianAppTranslation) // Ако е Българският превод.
    initBooksBulgarian();
  else // Ако е друг превод.
    initBooksEnglish();

  QString key1, str1;
  QString key2, str2;
  QString key3, str3;
  for (int index = 0; index < 77; index++)
  {
    key1 = QString("BookNameFull%1").arg(index+1);
    key2 = QString("BookNameShort%1").arg(index+1);
    key3 = QString("BookNameMin%1").arg(index+1);
    str1 = strSettings->value(key1, "").toString(); // Чете от TR файла.
    str2 = strSettings->value(key2, "").toString(); //
    str3 = strSettings->value(key3, "").toString(); //

    if (str1.isEmpty()) // Ако в TR файла няма такъв стринг.
      strSettings->setValue(key1, bookNameArr[index]); // Записва в TR файла.
    else
      bookNameArr[index] = str1;

    if (str2.isEmpty()) // Ако в TR файла няма такъв стринг.
      strSettings->setValue(key2, bookShortNameArr[index]); // Записва в TR файла.
    else
      bookShortNameArr[index] = str2;

    if (str3.isEmpty()) // Ако в TR файла няма такъв стринг.
      strSettings->setValue(key3, bookMinNameArr[index]); // Записва в TR файла.
    else
      bookMinNameArr[index] = str3;
  }
}

void TrStrings::setStr(QString &str, QString key, QString trBg, QString trEn)
{
  if (key.isEmpty()) return;
  str = strSettings->value(key, "").toString();
  if (str.isEmpty()) // Ако в TR файла няма такъв стринг.
  {
    if (isBulgarianAppTranslation) // Ако е Българският превод.
      str = trBg;
    else // Ако е друг превод.
      str = trEn;

    strSettings->setValue(key, str); // Записва в TR файла.
  }
}

void TrStrings::initializeStrings()
{
  QString appLayoutDirection = strSettings->value(QString("APP_LAYOUT_DIRECTION"), "").toString();
  appLayoutDirection = appLayoutDirection.toUpper();
  if (appLayoutDirection == QString("LEFTTORIGHT") || appLayoutDirection == QString("LEFT_TO_RIGHT"))
  {
    globalLayoutDirection = Qt::LeftToRight;
  }
  else if (appLayoutDirection == QString("RIGHTTOLEFT") || appLayoutDirection == QString("RIGHT_TO_LEFT"))
  {
    globalLayoutDirection = Qt::RightToLeft;
  }
  else
  {
    globalLayoutDirection = Qt::LeftToRight;
    strSettings->setValue(QString("APP_LAYOUT_DIRECTION"), QString("LeftToRight"));
  }

  bookFileNameArr[0]  = QString("Genesis");        
  bookFileNameArr[1]  = QString("Exodus");
  bookFileNameArr[2]  = QString("Leviticus");
  bookFileNameArr[3]  = QString("Numbers");
  bookFileNameArr[4]  = QString("Deuteronomy");
  bookFileNameArr[5]  = QString("Joshua");
  bookFileNameArr[6]  = QString("Judges");
  bookFileNameArr[7]  = QString("Ruth");
  bookFileNameArr[8]  = QString("1_Samuel");
  bookFileNameArr[9]  = QString("2_Samuel");
  bookFileNameArr[10] = QString("1_Kings");
  bookFileNameArr[11] = QString("2_Kings");
  bookFileNameArr[12] = QString("1_Chronicles");
  bookFileNameArr[13] = QString("2_Chronicles");
  bookFileNameArr[14] = QString("Ezra");
  bookFileNameArr[15] = QString("Nehemiah");
  bookFileNameArr[16] = QString("Esther");
  bookFileNameArr[17] = QString("Job");
  bookFileNameArr[18] = QString("Psalms");
  bookFileNameArr[19] = QString("Proverbs");
  bookFileNameArr[20] = QString("Ecclesiastes");
  bookFileNameArr[21] = QString("SongOfSolomon");
  bookFileNameArr[22] = QString("Isaiah");
  bookFileNameArr[23] = QString("Jeremiah");
  bookFileNameArr[24] = QString("Lamentations");
  bookFileNameArr[25] = QString("Ezekiel");
  bookFileNameArr[26] = QString("Daniel");
  bookFileNameArr[27] = QString("Hosea");
  bookFileNameArr[28] = QString("Joel");
  bookFileNameArr[29] = QString("Amos");
  bookFileNameArr[30] = QString("Obadiah");
  bookFileNameArr[31] = QString("Jonah");
  bookFileNameArr[32] = QString("Micah");
  bookFileNameArr[33] = QString("Nahum");
  bookFileNameArr[34] = QString("Habakkuk");
  bookFileNameArr[35] = QString("Zephaniah");
  bookFileNameArr[36] = QString("Haggai");
  bookFileNameArr[37] = QString("Zechariah");
  bookFileNameArr[38] = QString("Malachi");
  //
  bookFileNameArr[39] = QString("1_Esdras");
  bookFileNameArr[40] = QString("Tobit");
  bookFileNameArr[41] = QString("Judith");
  bookFileNameArr[42] = QString("Wisdom");
  bookFileNameArr[43] = QString("Sirach");
  bookFileNameArr[44] = QString("EpistleOfJeremiah");
  bookFileNameArr[45] = QString("Baruch");
  bookFileNameArr[46] = QString("1_Maccabees");
  bookFileNameArr[47] = QString("2_Maccabees");
  bookFileNameArr[48] = QString("3_4_Maccabees");
  bookFileNameArr[49] = QString("2_Esdras");
  //
  bookFileNameArr[50] = QString("Matthew");
  bookFileNameArr[51] = QString("Mark");
  bookFileNameArr[52] = QString("Luke");
  bookFileNameArr[53] = QString("John");
  bookFileNameArr[54] = QString("Acts");
  //
  bookFileNameArr[55] = QString("Romans");
  bookFileNameArr[56] = QString("1_Corinthians");
  bookFileNameArr[57] = QString("2_Corinthians");
  bookFileNameArr[58] = QString("Galatians");
  bookFileNameArr[59] = QString("Ephesians");
  bookFileNameArr[60] = QString("Philippians");
  bookFileNameArr[61] = QString("Colossians");
  bookFileNameArr[62] = QString("1_Thessalonians");
  bookFileNameArr[63] = QString("2_Thessalonians");
  bookFileNameArr[64] = QString("1_Timothy");
  bookFileNameArr[65] = QString("2_Timothy");
  bookFileNameArr[66] = QString("Titus");
  bookFileNameArr[67] = QString("Philemon");
  bookFileNameArr[68] = QString("Hebrews");
  //
  bookFileNameArr[69] = QString("James");
  bookFileNameArr[70] = QString("1_Peter");
  bookFileNameArr[71] = QString("2_Peter");
  bookFileNameArr[72] = QString("1_John");
  bookFileNameArr[73] = QString("2_John");
  bookFileNameArr[74] = QString("3_John");
  bookFileNameArr[75] = QString("Jude");
  //
  bookFileNameArr[76] = QString("Revelation");

  strSettings->beginGroup(QString("BookNames"));
    setBooksStr();
  strSettings->endGroup();

  strSettings->beginGroup(QString("Common"));
    setStr(Yes_v1, QString("Yes_v1"), QString("Да"), QString("Yes"));
    setStr(No_v1, QString("No_v1"), QString("Не"), QString("No"));
    setStr(OK_v1, QString("OK_v1"), QString("OK"), QString("OK"));
    setStr(Cancel_v1, QString("Cancel_v1"), QString("Отказ"), QString("Cancel"));
    setStr(Close_v1, QString("Close_v1"), QString("Затваря"), QString("Close"));
    setStr(CloseWindow_v1, QString("CloseWindow_v1"), QString("Затваря прозореца"), QString("Close Window"));
    setStr(MaximizeNormalize_v1, QString("MaximizeNormalize_v1"), QString("Максимизира/Нормализира"), QString("Maximize/Normalize"));
    setStr(HideToolBar_v1, QString("HideToolBar_v1"), QString("Скрива панела с инструменти"), QString("Hide the ToolBar"));
    setStr(DisabledDeuterocanonicalInfo_v1, QString("DisabledDeuterocanonicalInfo_v1"), QString("Книгата, която трябва да се покаже е Второканонична, а в момента Второканоничните книги са скрити!"), QString("This book is deuterocanonical. Deuterocanonical books are currently hidden!"));
    setStr(Book_v1, QString("Book_v1"), QString("Книга"), QString("Book"));
    setStr(Chapter_v1, QString("Chapter_v1"), QString("Глава"), QString("Chapter"));
  strSettings->endGroup();

  strSettings->beginGroup(QString("TMenu"));
    setStr(NewDockWindow_v1, QString("NewDockWindow_v1"), QString("Нов раздел"), QString("New Dock Window"));
    setStr(Books_v1, QString("Books_v1"), QString("Kниги"), QString("Books"));
    setStr(Bookmarks_v1, QString("Bookmarks_v1"), QString("Oтметки"), QString("Bookmarks"));
    setStr(BookShort_v1, QString("BookShort_v1"), QString("Кн"), QString("Bk"));
    setStr(ChapterShort_v1, QString("ChapterShort_v1"), QString("Гл"), QString("Ch"));
    setStr(VerseShort_v1, QString("VerseShort_v1"), QString("Ст"), QString("Vs"));
    setStr(DailyReadGroup_v1, QString("DailyReadGroup_v1"), QString("Режим на ежедневно четене.\nДен (група)."), QString("Daily Reading Mode.\nDay (Group)."));
    setStr(DailyReadChapterInGroup_v1, QString("DailyReadChapterInGroup_v1"), QString("Режим на ежедневно четене.\nГлава в групата."), QString("Daily Reading Mode.\nChapter in the Group."));
    setStr(GoBack_v1, QString("GoBack_v1"), QString("Преминава назад в историята на показаните глави"), QString("Go Back"));
    setStr(GoForward_v1, QString("GoForward_v1"), QString("Преминава напред в историята на показаните глави"), QString("Go Forward"));
    setStr(PreviousBook_v1, QString("PreviousBook_v1"), QString("Предходна книга"), QString("Previous Book"));
    setStr(NextBook_v1, QString("NextBook_v1"), QString("Следваща книга"), QString("Next Book"));
    setStr(NextPreviousBook_v1, QString("NextPreviousBook_v1"), QString("Следваща/Предходна книга"), QString("Next/Previous Book"));
    setStr(PreviousChapter_v1, QString("PreviousChapter_v1"), QString("Предходна глава"), QString("Previous Chapter"));
    setStr(NextChapter_v1, QString("NextChapter_v1"), QString("Следваща глава"), QString("Next Chapter"));
    setStr(NextPreviousChapter_v1, QString("NextPreviousChapter_v1"), QString("Следваща/Предходна глава"), QString("Next/Previous Chapter"));
    setStr(PreviousVerse_v1, QString("PreviousVerse_v1"), QString("Предходен стих"), QString("Previous Verse"));
    setStr(NextVerse_v1, QString("NextVerse_v1"), QString("Следващ стих"), QString("Next Verse"));
    setStr(NextPreviousVerse_v1, QString("NextPreviousVerse_v1"), QString("Следващ/Предходен стих"), QString("Next/Previous Verse"));
    setStr(PreviousChaptersDailyRead_v1, QString("PreviousChaptersDailyRead_v1"), QString("Режим на ежедневно четене.\nПоказва предходната група (прочетени) глави."), QString("Daily Reading Mode.\nPrevious Group of (read) Chapters."));
    setStr(NextChaptersDailyRead_v1, QString("NextChaptersDailyRead_v1"), QString("Режим на ежедневно четене.\nПоказва следващата група глави за четене."), QString("Daily Reading Mode.\nNext Group of Chapters to read."));
    setStr(PreviousChapterDailyRead_v1, QString("PreviousChapterDailyRead_v1"), QString("Режим на ежедневно четене.\nПоказва предходната глава от групата."), QString("Daily Reading Mode.\nPrevious Chapter in the Group."));
    setStr(NextChapterDailyRead_v1, QString("NextChapterDailyRead_v1"), QString("Режим на ежедневно четене.\nПоказва следващата глава от групата."), QString("Daily Reading Mode.\nNext Chapter in the Group."));
    setStr(DailyRead_v1, QString("DailyRead_v1"), QString("Режим на ежедневно четене"), QString("Daily Reading Mode"));
    setStr(SearchInBible_v1, QString("SearchInBible_v1"), QString("Търсене в Библията"), QString("Search in the Bible"));
    setStr(BibleTexts_v1, QString("BibleTexts_v1"), QString("Налични текстове на Библията"), QString("Available Bible Texts"));
    setStr(Audio_v1, QString("Audio_v1"), QString("Аудио"), QString("Audio"));
    setStr(ZoomInText_v1, QString("ZoomInText_v1"), QString("Увеличава размера на текста"), QString("Zoom Text In"));
    setStr(ZoomOutText_v1, QString("ZoomOutText_v1"), QString("Намалява размера на текста"), QString("Zoom Text Out"));
    setStr(RestoreDefaultZoom_v1, QString("RestoreDefaultZoom_v1"), QString("Нормализира размера на текста"), QString("Restore Default Zoom level"));
    setStr(SelectAll_v1, QString("SelectAll_v1"), QString("Селектира целия текст"), QString("Select All"));
    setStr(Copy_v1, QString("Copy_v1"), QString("Копира селектирания текст"), QString("Copy"));
    setStr(Search_v1, QString("Search_v1"), QString("Търси"), QString("Search"));
    setStr(SearchInTheTextPanel_v1, QString("SearchInTheTextPanel_v1"), QString("Панел за търсене в показания текст"), QString("Search in Displayed Text Panel"));
    setStr(SearchInTheText_v1, QString("SearchInTheText_v1"), QString("Търси в показания текст"), QString("Search in the displayed text"));
    setStr(FindPrevious_v1, QString("FindPrevious_v1"), QString("Търси назад"), QString("Find Previous"));
    setStr(FindNext_v1, QString("FindNext_v1"), QString("Търси напред"), QString("Find Next"));
    setStr(CaseSensitive_v1, QString("CaseSensitive_v1"), QString("Различава главни/малки букви"), QString("Case Sensitive"));
    setStr(WholeWords_v1, QString("WholeWords_v1"), QString("Само цяла (точна) дума"), QString("Whole Words Only"));
    setStr(StatisticsMenu_v1, QString("StatisticsMenu_v1"), QString("Статистика"), QString("Statistics"));
    setStr(CompareTwoTexts_v1, QString("CompareTwoTexts_v1"), QString("Сравнява два текста"), QString("Compare Two Texts"));
    setStr(UniqueWordsInBible_v1, QString("UniqueWordsInBible_v1"), QString("Уникални думи в цялата Библия"), QString("Unique words in the whole Bible"));
    setStr(UniqueWordsInOT_v1, QString("UniqueWordsInOT_v1"), QString("Уникални думи в Стария Завет"), QString("Unique words in the Old Testament"));
    setStr(UniqueWordsInNT_v1, QString("UniqueWordsInNT_v1"), QString("Уникални думи в Новия Завет"), QString("Unique words in the New Testament"));
    setStr(UniqueWordsInBook_v1, QString("UniqueWordsInBook_v1"), QString("Уникални думи в текущата книга"), QString("Unique words in the current book"));
    setStr(UniqueWordsInChapter_v1, QString("UniqueWordsInChapter_v1"), QString("Уникални думи в текущата глава"), QString("Unique words in the current chapter"));
    setStr(Pad_v1, QString("Pad_v1"), QString("Бележник"), QString("Pad"));
    setStr(DictionaryCommentary_v1, QString("DictionaryCommentary_v1"), QString("Речник/коментар"), QString("Dictionary/Commentary"));
    setStr(ExternalImages_v1, QString("ExternalImages_v1"), QString("Външни изображения (карти, схеми, диаграми...)"), QString("External Images (Maps, Drawings, Diagrams...)"));
    setStr(Projector_v1, QString("Projector_v1"), QString("Проектор"), QString("Projector"));
    setStr(Links_v1, QString("Links_v1"), QString("Ресурси в Интернет"), QString("Links"));
    setStr(Settings_v1, QString("Settings_v1"), QString("Настройки"), QString("Settings"));
    setStr(Help_v1, QString("Help_v1"), QString("Помощна информация"), QString("Help"));
    setStr(About_v1, QString("About_v1"), QString("Информация за MatCrossBible"), QString("About MatCrossBible"));
    setStr(CheckNewAppVersion_v1, QString("CheckNewAppVersion_v1"), QString("Проверка за нова версия"), QString("Check for New App Version"));
    setStr(FileMenu_v1, QString("FileMenu_v1"), QString("Меню Файл: Експорт, печат..."), QString("Menu File: Export, print..."));
    setStr(ExportToText_v1, QString("ExportToText_v1"), QString("Запис като текст..."), QString("Export to Text..."));
    setStr(ExportToHTML_v1, QString("ExportToHTML_v1"), QString("Запис като HTML..."), QString("Export to HTML..."));
    setStr(ExportToPDF_v1, QString("ExportToPDF_v1"), QString("Запис като PDF..."), QString("Export to PDF..."));
    setStr(PrintPreview_v1, QString("PrintPreview_v1"), QString("Преглед преди отпечатване"), QString("Print Preview"));
    setStr(Print_v1, QString("Print_v1"), QString("Отпечатване..."), QString("Print..."));
    setStr(Session_v1, QString("Session_v1"), QString("Сесия"), QString("Session"));
    setStr(CloseDockWindow_v1, QString("CloseDockWindow_v1"), QString("Затваря раздела"), QString("Close Window"));
    setStr(Exit_v1, QString("Exit_v1"), QString("Изход от програмата"), QString("Exit"));
  strSettings->endGroup();

  strSettings->beginGroup(QString("BibleTextsToolBar"));
    setStr(RearrangeBibletexts_v1, QString("RearrangeBibletexts_v1"), QString("Променя реда на текстовете"), QString("Rearrange Bible texts"));
    setStr(Info_v1, QString("Info_v1"), QString("Инфо"), QString("Info"));
    setStr(BibleTextsInfo_v1, QString("BibleTextsInfo_v1"), QString("Информация за наличните текстове на Библията"), QString("Bible Texts Info"));
    setStr(More_v1, QString("More_v1"), QString("Други"), QString("More"));
    setStr(DownloadMoreBibleTexts_v1, QString("DownloadMoreBibleTexts_v1"), QString("Изтегляне на други Библейски текстове"), QString("Download more Bible texts"));
    setStr(MoreBibleTexts_v1, QString("MoreBibleTexts_v1"), QString("Други Библейски текстове"), QString("More Bible Texts"));
    setStr(Convert_v1, QString("Convert_v1"), QString("Конверт"), QString("Convert"));
    setStr(ConvertBibleTexts_v1, QString("ConvertBibleTexts_v1"), QString("Конвертира Библейски текстове от други софтуерни програми"), QString("Convert Bible texts from other software"));
    setStr(ConvertCrossBgBibleFile_v1, QString("ConvertCrossBgBibleFile_v1"), QString("Конвертиране на текст от стара версия на CrossBgBible (STRUCTURE_VERSION=1)"), QString("Convert Bible texts from old CrossBgBible app versions (STRUCTURE_VERSION=1)"));
    setStr(ConvertTheWordFile_v1, QString("ConvertTheWordFile_v1"), QString("Конвертиране на текст от програмата TheWord (*.ont, *.nt, *.ot)"), QString("Convert Bible texts from TheWord (*.ont, *.nt, *.ot)"));
    setStr(ChooseFile_v1, QString("ChooseFile_v1"), QString("Избери файл"), QString("Choose File"));
    setStr(ConvertFileToUTF8First_v1, QString("ConvertFileToUTF8First_v1"), QString("Файлът трябва да бъде предварително конвертиран в UTF-8 формат!"), QString("File must be converted to UTF-8 first!"));
    setStr(AddNumbersToVerses_v1, QString("AddNumbersToVerses_v1"), QString("Добавя номера на стиховете (всеки стих приема пореден номер от текущата глава)"), QString("Add numbers to verses (every verse receives a sequent number from the current chapter)"));
    setStr(UnknownFileFormat_v1, QString("UnknownFileFormat_v1"), QString("Файлът е в непознат формат!"), QString("Unknown file format!"));
    setStr(ConversionSuccessful_v1, QString("ConversionSuccessful_v1"), QString("Конвертирането завърши успешно!"), QString("Conversion successful!"));
  strSettings->endGroup();

  strSettings->beginGroup(QString("AudioToolBar"));
    setStr(NoAudioForThisChapter_v1, QString("NoAudioForThisChapter_v1"), QString("Няма аудио за тази глава."), QString("No audio for this chapter."));
    setStr(NoAudioForThisBook_v1, QString("NoAudioForThisBook_v1"), QString("Няма аудио за тази книга."), QString("No audio for this book."));
    setStr(PlayChapter_v1, QString("PlayChapter_v1"), QString("Тази глава"), QString("This Chapter"));
    setStr(PlayChapterTT_v1, QString("PlayChapterTT_v1"), QString("Прослушване на текущата глава"), QString("Play Current Chapter"));
    setStr(PlayBook_v1, QString("PlayBook_v1"), QString("Тази книга"), QString("This Book"));
    setStr(PlayBookTT_v1, QString("PlayBookTT_v1"), QString("Прослушване на текущата книга"), QString("Play Current Book"));
    setStr(PlayGroup_v1, QString("PlayGroup_v1"), QString("Тази група"), QString("This Group"));
    setStr(PlayGroupTT_v1, QString("PlayGroupTT_v1"), QString("Прослушване на текущата група глави (в режим на ежедневно четене)"), QString("Play Current Group of Chapters (In Daily Reading Mode Only)"));
    setStr(Stop_v1, QString("Stop_v1"), QString("Стоп"), QString("Stop"));
    setStr(Pause_v1, QString("Pause_v1"), QString("Пауза"), QString("Pause"));
    setStr(Repeat_v1, QString("Repeat_v1"), QString("Повторение на главата/книгата"), QString("Repeat Chapter/Book"));
    setStr(Seek_v1, QString("Seek_v1"), QString("Прогрес"), QString("Seek"));
    setStr(Rate_v1, QString("Rate_v1"), QString("Скорост на прослушване"), QString("Speed"));
    setStr(Volume_v1, QString("Volume_v1"), QString("Сила на звука"), QString("Volume"));
    setStr(Synchronize_v1, QString("Synchronize_v1"), QString("Синхронизиране на текущо прослушваната глава с текста\n(ще се показва главата, която се прослушва в момента)"), QString("Sincronize the currently played chapter with the text\n(currently played chapter will be displayed)"));
    setStr(CurrentChapter_v1, QString("CurrentChapter_v1"), QString("Текуща глава"), QString("Current Chapter"));
    setStr(AllChapters_v1, QString("AllChapters_v1"), QString("Всички глави"), QString("All Chapters"));
    setStr(TargetAudioText_v1, QString("TargetAudioText_v1"), QString("Задава текста, който ще се слуша."), QString("Choose text to play"));
    setStr(IncorrectAudioLocationFile_v1, QString("IncorrectAudioLocationFile_v1"), QString("Този AudioLocation файл може да е празен или да не е попълнен коректно!"), QString("This AudioLocation file is empty or incorrectly filled in!"));
	setStr(EditALF_v1, QString("EditALF_v1"), QString("Редактиране"), QString("Edit"));
	setStr(EditALFTT_v1, QString("EditALFTT_v1"), QString("Редактиране на текущия AudioLocation файл"), QString("Edit current AudioLocation file"));
	setStr(NewALF_v1, QString("NewALF_v1"), QString("Нов"), QString("New"));
	setStr(NewALFTT_v1, QString("NewALFTT_v1"), QString("Създаване на празен AudioLocation файл"), QString("Create blank AudioLocation file"));
	setStr(DeleteALF_v1, QString("DeleteALF_v1"), QString("Изтрива файла"), QString("Delete file"));
	setStr(DeleteALFTT_v1, QString("DeleteALFTT_v1"), QString("Изтрива текущия AudioLocation файл"), QString("Delete current AudioLocation file"));
	setStr(DeleteALFQuestion_v1, QString("DeleteALFQuestion_v1"), QString("Да бъде ли изтрит този AudioLocation файл?"), QString("Do you want to delete this AudioLocation file?")); // Are you sure you want to delete this AudioLocation file?
    setStr(DownloadAudioBible_v1, QString("DownloadAudioBible_v1"), QString("Изтегляне..."), QString("Download..."));
    setStr(DownloadAudioBibleTT_v1, QString("DownloadAudioBibleTT_v1"), QString("Изтегляне на Аудио Библията на локалния диск"), QString("Download Audio Bible to local disk"));
    setStr(TargetDirChoose_v1, QString("TargetDirChoose_v1"), QString("Избор на директория"), QString("Choose target folder"));
    setStr(AutoFillLocalPath_v1, QString("AutoFillLocalPath_v1"), QString("Автоматично попълване на AudioLocation файла (колона Local Path на таблицата). Това ще изтрие съществуващите записи!"), QString("Automatically fill in the AudioLocation file (column Local Path of the spreadsheet). This will erase all existing records!"));
    setStr(TargetDirNotExist_v1, QString("TargetDirNotExist_v1"), QString("Избраната директория не съществува!"), QString("Target folder does not exist!"));
    setStr(MakeDirProblem_v1, QString("MakeDirProblem_v1"), QString("Има проблем при създаване на поддиректориите!"), QString("There has been a problem with the creation of the Subfolders!"));
    setStr(NoUrlPaths_v1, QString("NoUrlPaths_v1"), QString("Няма зададен нито един URL адрес!"), QString("No URL has been set!"));
    setStr(NoFileNames_v1, QString("NoFileNames_v1"), QString("Зададените URL адреси нямат ясно изписани имена на файлове!"), QString("Chosen URLs do not have clearly written file names!"));
    setStr(DownloadedFileCount_v1, QString("DownloadedFileCount_v1`"), QString("Брой на изтеглените файлове:"), QString("Downloaded files count:"));
    setStr(ALFEditor_v1, QString("ALFEditor_v1"), QString("AudioLocationFile (ALF) Редактор"), QString("AudioLocationFile (ALF) Editor"));
    setStr(ALFShortDescription_v1, QString("ALFShortDescription_v1"), QString("Кратко описание:"), QString("Short Description:"));
    setStr(ALFFileName_v1, QString("ALFFileName_v1"), QString("Име на файла:"), QString("File Name:"));
  strSettings->endGroup();

  strSettings->beginGroup(QString("Session"));
    setStr(StandardSession_v1, QString("StandardSession_v1"), QString("Стандартна сесия"), QString("Standard Session"));
    setStr(SaveSession_v1, QString("SaveSession_v1"), QString("Запомня състоянието на прозореца и отворените раздели в тази сесия"), QString("Save Session"));
    setStr(LoadSession_v1, QString("LoadSession_v1"), QString("Зарежда сесията"), QString("Load Session"));
    setStr(CurrentSession_v1, QString("CurrentSession_v1"), QString("Текуща сесия"), QString("Current Session"));
  strSettings->endGroup();

  strSettings->beginGroup(QString("BookmarksWidget"));
    setStr(AddBookmark_v1, QString("AddBookmark_v1"), QString("Кликване с мишката в празно поле ще добави отметка към текущия стих."), QString("Left mouse click on the empty field will add a bookmark to current verse."));
    setStr(ShowBookmark_v1, QString("ShowBookmark_v1"), QString("Кликване върху отметка ще я покаже в текущия раздел."), QString("Left mouse click on bookmark will display it in current dock window."));
    setStr(DeleteBookmark_v1, QString("DeleteBookmark_v1"), QString("Изтриване на отметка става, като се натисне бутонът за изтриване до нея (X)."), QString("To delete a bookmark press (X)."));
    setStr(DeleteBookmarkQuestion_v1, QString("DeleteBookmarkQuestion_v1"), QString("Да бъде ли изтрита тази отметка?"), QString("Do you want to delete this bookmark?")); // Are you sure you want to delete this bookmark?
  strSettings->endGroup();

  strSettings->beginGroup(QString("ProjectorToolBar"));
    setStr(HideText_v1, QString("HideText_v1"), QString("Скрива текста"), QString("Hide Text"));
    setStr(LockScreen_v1, QString("LockScreen_v1"), QString("Заключва екрана"), QString("Lock Screen"));
    setStr(HideTheName_v1, QString("HideTheName_v1"), QString("Скрива името"), QString("Hide Name"));
    setStr(TextColor_v1, QString("TextColor_v1"), QString("Цвят на текста"), QString("Text Color"));
    setStr(CustomFont_v1, QString("CustomFont_v1"), QString("Собствен шрифт"), QString("Custom Font"));
    setStr(EnableCustomFont_v1, QString("EnableCustomFont_v1"), QString("Разрешава собствен шрифт"), QString("Enable Custom Font"));
    setStr(Left_v1, QString("Left_v1"), QString("Ляво"), QString("Left"));
    setStr(Center_v1, QString("Center_v1"), QString("Център"), QString("Center"));
    setStr(Right_v1, QString("Right_v1"), QString("Дясно"), QString("Right"));
    setStr(Top_v1, QString("Top_v1"), QString("Горе"), QString("Top"));
    setStr(Bottom_v1, QString("Bottom_v1"), QString("Долу"), QString("Bottom"));
    setStr(TextOutlineShadow_v1, QString("TextOutlineShadow_v1"), QString("Контур (o-Outline) / Сянка (s-Shadow) на текста"), QString("Text Outline (o) / Shadow (s)"));
    setStr(OutlineShadowColor_v1, QString("OutlineShadowColor_v1"), QString("Цвят на контура/сянката"), QString("Outline/Shadow Color"));
    setStr(LeftTitleBar_v1, QString("LeftTitleBar_v1"), QString("Лява заглавна лента"), QString("Left Title Bar"));
    setStr(TopTitleBar_v1, QString("TopTitleBar_v1"), QString("Горна заглавна лента"), QString("Top Title Bar"));
    setStr(RightTitleBar_v1, QString("RightTitleBar_v1"), QString("Дясна заглавна лента"), QString("Right Title Bar"));
    setStr(BottomTitleBar_v1, QString("BottomTitleBar_v1"), QString("Долна заглавна лента"), QString("Bottom Title Bar"));
    setStr(SemiTransparentTitleBar_v1, QString("SemiTransparentTitleBar_v1"), QString("Полупрозрачна заглавна лента"), QString("Semi-transparent Title Bar"));
    setStr(TransparentTitleBar_v1, QString("TransparentTitleBar_v1"), QString("Прозрачна заглавна лента"), QString("Transparent Title Bar"));
    setStr(PicFit_v1, QString("PicFit_v1"), QString("Съразмерно"), QString("Fit"));
    setStr(PicFitEx_v1, QString("PicFitEx_v1"), QString("Съразмерно, разширено"), QString("Fit Expanding"));
    setStr(PicStretch_v1, QString("PicStretch_v1"), QString("Разтеглено"), QString("Stretch"));
    setStr(PicCenter_v1, QString("PicCenter_v1"), QString("1:1"), QString("1:1"));
    setStr(EmbededPicture_v1, QString("EmbededPicture_v1"), QString("Вградено изображение"), QString("Embeded Picture"));
    setStr(ExternalPicture_v1, QString("ExternalPicture_v1"), QString("Външно изображение"), QString("External Picture"));
    setStr(Brightness_v1, QString("Brightness_v1"), QString("Яркост на кръговете"), QString("Brightness"));
    setStr(Color_v1, QString("Color_v1"), QString("Цвят"), QString("Color"));
    setStr(SaveAsPic_v1, QString("SaveAsPic_v1"), QString("Записва текущия екран като картинка"), QString("Save current screen as image"));
  strSettings->endGroup();

  strSettings->beginGroup(QString("SearchToolBar"));
    setStr(SearchInBibleTargetText_v1, QString("SearchInBibleTargetText_v1"), QString("Текст, в който ще се търси"), QString("Target Bible Text"));
    setStr(ShowHideOptions_v1, QString("ShowHideOptions_v1"), QString("Показва/скрива опциите за търсене в Библията"), QString("Show/hide Bible search options"));
    setStr(OptSearchRandom_v1, QString("OptSearchRandom_v1"), QString("Търси част от дума"), QString("Match part of word"));
    setStr(OptSearchRandomTT_v1, QString("OptSearchRandomTT_v1"), QString("Търси част от дума"), QString("Match part of word"));
    setStr(OptSearchRoot_v1, QString("OptSearchRoot_v1"), QString("Търси корен (начало) на дума"), QString("Match root (beginning) of word"));
    setStr(OptSearchRootTT_v1, QString("OptSearchRootTT_v1"), QString("Търси корен (начало) на дума"), QString("Match root (beginning) of word"));
    setStr(OptSearchWord_v1, QString("OptSearchWord_v1"), QString("Търси точна дума"), QString("Match whole words only"));
    setStr(OptSearchWordTT_v1, QString("OptSearchWordTT_v1"), QString("Търси точна дума"), QString("Match whole words only"));
    setStr(OptSearchAll_v1, QString("OptSearchAll_v1"), QString("Всички търсени думи"), QString("All searched words"));
    setStr(OptSearchAllTT_v1, QString("OptSearchAllTT_v1"), QString("В стиха да се съдържат всички търсени думи"), QString("The verse must contain all words"));
    setStr(OptSearchAny_v1, QString("OptSearchAny_v1"), QString("Поне една от думите"), QString("One or more words"));
    setStr(OptSearchAnyTT_v1, QString("OptSearchAnyTT_v1"), QString("В стиха да се съдържа поне една от търсените думите"), QString("The verse must contain at least one of the words"));
    setStr(OptSearchPhrase_v1, QString("OptSearchPhrase_v1"), QString("Цяла фраза"), QString("Whole phrase"));
    setStr(OptSearchPhraseTT_v1, QString("OptSearchPhraseTT_v1"), QString("Търсените думи се третират като една неделима фраза"), QString("Searched words will be treated as a single phrase"));
    setStr(OptSearchWildCard_v1, QString("OptSearchWildCard_v1"), QString("Разширено търсене (чрез ? и *)"), QString("Use Wildcards (? and *)"));
    setStr(OptSearchWildCardTT_v1, QString("OptSearchWildCardTT_v1"), QString("Разширено търсене\nИзползват се специалните символи ? и *\n  ? - замества една, коя да е буква\n  * - замества неограничен брой букви"), QString("Wildcards\nThe special characters ? and * are used\n  ? - Any single character\n  * - Zero or more of any character"));
    setStr(OptSearchCaseSensitive_v1, QString("OptSearchCaseSensitive_v1"), QString("Различава главни/малки букви"), QString("Match case"));
    setStr(OptSearchCaseInsensitive_v1, QString("OptSearchCaseInsensitive_v1"), QString("Не различава главни/малки букви"), QString("Does not match case"));
    setStr(OptSearchCaseSensitivityTT_v1, QString("OptSearchCaseSensitivityTT_v1"), QString("Различава или не главни/малки букви"), QString("Matches or does not match case"));
    setStr(OptSearchInChapter_v1, QString("OptSearchInChapter_v1"), QString("Търси в глава"), QString("Search within chapter"));
    setStr(OptSearchInChapterTT_v1, QString("OptSearchInChapterTT_v1"), QString("Търсените думи не се търсят в стих, а в глава\n(все едно всички стихове от една глава са един голям стих)"), QString("Search words within a chapter instead of a verse\n (As if all the verses in a chapter are one long verse)"));
    setStr(VersesContainAllSearchedWords_v1, QString("VersesContainAllSearchedWords_v1"), QString("Стихове, съдържащи всички търсени думи:"), QString("Verses containing all searched words:"));
    setStr(VersesContainAnySearchedWord_v1, QString("VersesContainAnySearchedWord_v1"), QString("Стихове, съдържащи поне една от думите:"), QString("Verses containing at least one of the words:")); 
    setStr(VersesContainSearchedPhrase_v1, QString("VersesContainSearchedPhrase_v1"), QString("Стихове, съдържащи фразата:"), QString("Verses containing the phrase:"));
    setStr(ChaptersContainAllSearchedWords_v1, QString("ChaptersContainAllSearchedWords_v1"), QString("Глави, съдържащи всички търсени думи:"), QString("Chapters containing all searched words:"));
    setStr(ChaptersContainAnySearchedWord_v1, QString("ChaptersContainAnySearchedWord_v1"), QString("Глави, съдържащи поне една от думите:"), QString("Chapters containing at least one of the words:"));
    setStr(ChaptersContainSearchedPhrase_v1, QString("ChaptersContainSearchedPhrase_v1"), QString("Глави, съдържащи фразата:"), QString("Chapters containing the phrase:"));
    setStr(TotalOf_v1, QString("TotalOf_v1"), QString("от общо"), QString("of"));
    setStr(Total_v1, QString("Total_v1"), QString("Общо"), QString("Total"));
    setStr(InTheFoundVerses_v1, QString("InTheFoundVerses_v1"), QString("В откритите стихове:"), QString("In the found verses:"));
    setStr(InTheFoundChapters_v1, QString("InTheFoundChapters_v1"), QString("В откритите глави:"), QString("In the found chapters:"));
    setStr(AllBooks_v1, QString("AllBooks_v1"), QString("Всички книги"), QString("All Books"));
    setStr(TheOldTestament_v1, QString("TheOldTestament_v1"), QString("Стария Завет"), QString("The Old Testament"));
    setStr(TheNewTestament_v1, QString("TheNewTestament_v1"), QString("Новия Завет"), QString("The New Testament"));
    setStr(OT_v1, QString("OT_v1"), QString("С.З."), QString("O.T."));
    setStr(NT_v1, QString("NT_v1"), QString("Н.З."), QString("N.T."));
    setStr(Filter_v1, QString("Filter_v1"), QString("Филтър"), QString("Filter"));
    setStr(Results_v1, QString("Results_v1"), QString("Резултати"), QString("Results"));
    setStr(TooManyMatches_v1, QString("TooManyMatches_v1"), QString("Открити са над 2500 стиха!"), QString("More than 2500 verses found!"));
    setStr(UseFilter_v1, QString("UseFilter_v1"), QString("Използвайте филтъра за детайлно разглеждане на резултата по книги."), QString("Use filter for detailed viewing of the results by books."));
    setStr(NoMatchesVerses_v1, QString("NoMatchesVerses_v1"), QString("Няма стихове с това съдържание!"), QString("No verses found!"));
    setStr(NoMatchesChapters_v1, QString("NoMatchesChapters_v1"), QString("Няма глави с това съдържание!"), QString("No chapters found!"));
    setStr(ChangeSearchOptions_v1, QString("ChangeSearchOptions_v1"), QString("Можете да изберете друг текст или опция за търсене."), QString("You can choose another text or search option."));
    setStr(SearchError_v1, QString("SearchError_v1"), QString("Грешка при търсене!"), QString("Search error!"));
    setStr(Map_v1, QString("Map_v1"), QString("Карта"), QString("Map"));
    setStr(Deuterocanonical_v1, QString("Deuterocanonical_v1"), QString("Второканонична"), QString("Deuterocanonical"));
    setStr(SearchMethodInfo1_v1, QString("SearchMethodInfo1_v1"), QString("Напишете търсените думи в полето горе, изберете текста и опциите за търсене и натиснете бутона за търсене."), QString("Enter key words into the above field, choose the text and search options and press the search button."));
    setStr(SearchMethodInfo2_v1, QString("SearchMethodInfo2_v1"), QString("Опции за търсене:"), QString("Search options:"));
    setStr(SearchMethodInfo31_v1, QString("SearchMethodInfo31_v1"), QString("Това е най-универсалният метод за търсене защото при него не се налагат никакви ограничения на търсенето (филтри). При този метод се търси част от дума. Например, ако се търси <b><u>питах</u></b>, ще бъдат показани всички стихове, които съдържат думата <b><u>питах</u></b>, <b><u>питах</u>а</b>, <b>по<u>питах</u></b>, <b>из<u>питах</u>а</b> и т.н."), QString("This is the most universal search method as it does not use any search restrictions (Filters). This method searches for part of a word. For example, if the word <b><u>root</u></b> is searched, will return all verses that contain the words <b><u>root</u></b>, <b><u>root</u>ing</b>, <b>up<u>root</u>ed</b> etc."));
    setStr(SearchMethodInfo32_v1, QString("SearchMethodInfo32_v1"), QString("При този метод резултатите ще са винаги твърде много, но за сметка на това той е подходящ за извличане на по-особени статистически данни, като например колко пъти се среща дадена буква или знак в цялата Библия. При него могат да се търсят и специални знаци, като звездичка, скоба, тире, въпросителен знак, кавички и т.н., а също така може да се правят комбинации между различни букви и знаци, като например <b><u>казаха:</u></b>."), QString("The results from this method will always be too many, although despite that it is useful for more specific statistical data, such as number of mathes for a given character in the whole Bible. You can also search special symbols such as asterisk, parenthesis, dash, question mark, quotes, etc., as well as any combination between different letters and symbols, e.g. \"<b><u>He said:</u></b>\"."));
    setStr(SearchMethodInfo33_v1, QString("SearchMethodInfo33_v1"), QString("Ако се търсят няколко думи (или части от думи), те трябва да се разделят с интервали. Например ако в полето за търсене се напише <b><u>за когото</u></b>, то няма да се търси фразата \"<b><u>за когото</u></b>\", а ще се търси и покаже всеки стих, който съдържа двете думи: <b><u>за</u></b> и <b><u>когото</u></b>. Това е препоръчителният метод за търсене."), QString("If the search includes several words (or parts) they must be separated with spaces. Searching for <b><u>for him</u></b>, will not return the phrase \"<b><u>for him</u></b>\", but will display every verse that contains both words: <b><u>for</u></b> and <b><u>him</u></b>. This is the preffered search method."));
    setStr(SearchMethodInfo41_v1, QString("SearchMethodInfo41_v1"), QString("При този метод на търсене ще се покажат всички стихове, които съдържат думи започващи с търсената дума. За пример, ако се търси <b><u>питах</u></b>, ще бъдат показани всички стихове, които съдържат думата <b><u>питах</u></b>, <b><u>питах</u>а</b>, <b><u>питах</u>ме</b>, <b><u>питах</u>те</b> и т.н."), QString("This method will return all verses containing words that begin with the searched word. For instance, searching for <b><u>ask</u></b>, will return all verses that contain the words <b><u>ask</u></b>, <b><u>ask</u>ed</b>, <b><u>ask</u>ing</b>, etc."));
    setStr(SearchMethodInfo42_v1, QString("SearchMethodInfo42_v1"), QString("При този метод, всички знаци различни от буквите и цифрите се третират като разделител. Т.е. тук не могат да се търсят специални знаци или комбинация от букви и знаци. Това е един от най-популярните методи за търсене, но въпреки това не се препоръчва."), QString("All characters that are not letters or numbers are treated as dividers. No special symbols may be searched, or letters and symbols combination. This is one of the more popular search methods, although it is not recommended."));
    setStr(SearchMethodInfo51_v1, QString("SearchMethodInfo51_v1"), QString("При този метод на търсене ще се покажат всички стихове, които съдържат точно търсената дума. За пример, ако се търси <b><u>питах</u></b>, ще бъдат показани само стиховете, които съдържат думата <b><u>питах</u></b>."), QString("Search method will return all verses that contain the searched word. For example, searching for <b><u>ask</u></b> will only dispaly verses containing the word <b><u>ask</u></b>."));
    setStr(SearchMethodInfo52_v1, QString("SearchMethodInfo52_v1"), QString("И при този метод всички знаци различни от буквите и цифрите се третират като разделител. Т.е. тук не могат да се търсят специални знаци или комбинация от букви и знаци. Това е един от най-ограничаващите (филтриращи) методи на търсене и трябва да се използва само в краен случай (когато другите методи връщат много резултати)."), QString("Again, all characters that are not letters or numbers are considered dividers. No special symbols may be searched. This is one of the most restricting (filtering) search methods and should only be used if the other methods return too many results."));
    setStr(SearchMethodInfo61_v1, QString("SearchMethodInfo61_v1"), QString("Тази опция е от значение само когато в полето за търсене са написани повече от една думи. Когато трябва да се намерят стиховете, които съдържат задължително всички търсени думи се избира \"<i>Всички търсени думи</i>\", а ако трябва да се намерят стиховете, които съдържат поне една от търсените думи се избира \"<i>Поне една от думите</i>\"."), QString("This option is relevant only when more than one word is searched for. If the verses containing all the words are wanted, the \"<i>All searched words</i>\" option is selected, while if only those that contain at least one of the words, then select \"<i>One or more words</i>\"."));
    setStr(SearchMethodInfo62_v1, QString("SearchMethodInfo62_v1"), QString(""), QString("")); // Да се премахне този стринг!!!!!!!!!!!
    setStr(SearchMethodInfo71_v1, QString("SearchMethodInfo71_v1"), QString("Ако е избрана тази опция, всичко което е написано в полето за търсене се приема като едно цяло. За пример: ако в полето за търсене е написано <b><u>за когото</u></b>, то няма да се търси по отделно думата <b><u>за</u></b> и думата <b><u>когото</u></b>, а ще се търси и покаже всеки стих, който съдържа точно фразата \"<b><u>за когото</u></b>\". С две думи, тук интервалът не се приема за разделител, а се третира като буква."), QString("This option treats all words as one. For example, if <b><u>king David</u></b> is searched, it will not display verses with <b><u>king</u></b> and <b><u>David</u></b> separately, but only those that contain the phrase \"<b><u>king David</u></b>\". The space is considered a character, not a divider."));
    setStr(SearchMethodInfo72_v1, QString("SearchMethodInfo72_v1"), QString("Важно е да се отбележи, че заграждането на търсените думи в кавички няма да доведе до търсене на фраза както е в стандартните търсачки. Задължително трябва да се маркира опцията \"<i>Цяла фраза</i>\" ако трябва да се търси фраза."), QString("It is important to note that putting a phrase between quotes will not search for a phrase, as is with most search engines. The \"<i>Whole phrase</i>\" option must be selected."));
    setStr(SearchMethodInfo81_v1, QString("SearchMethodInfo81_v1"), QString("Това е един специален вид търсене, който третира по особен начин звездичката и въпросителния знак. Наличието на звездичка някъде в търсената дума означава, че на мястото на тази звездичка може да няма нищо или да има неограничен брой букви (само букви, без символи и интервали), а наличието на въпросителен знак означава, че на негово място може да има точно една, каква да е буква."), QString("This is a special search method where the asterisk replaces either nothing or any number of letters (no symbols or spaces), while the question mark replaces any single letter."));
    setStr(SearchMethodInfo82_v1, QString("SearchMethodInfo82_v1"), QString("За пример: <b><u>ко?то</u></b> ще покаже всички стихове, които съдържат <b><u>ко</u>й<u>то</u></b>, <b><u>ко</u>я<u>то</u></b> и т.н., докато <b><u>ко*то</u></b> ще покаже освен <b><u>ко</u>й<u>то</u></b> и <b><u>ко</u>я<u>то</u></b>, също и <b><u>ко</u>го<u>то</u></b>, <b><u>ко</u>лко<u>то</u></b> и т.н. Друг пример - ако се напише <b><u>\"*\"</u></b> ще върне всяка дума заградена в кавички, а ако се напише <b><u>\"* *\"</u></b> ще върне две думи заградени в кавички и т.н."), QString("For example: <b><u>?ow</u></b> will return all verses containing <b>h<u>ow</u></b>, <b>l<u>ow</u></b>, <b>n<u>ow</u></b> etc., while <b><u>*ow</u></b> will display <b>h<u>ow</u></b> and <b>l<u>ow</u></b>, as well as <b>wind<u>ow</u></b> and <b>sn<u>ow</u></b>, etc. Another example - typing <b><u>\"*\"</u></b> will return all words surrounded by quotes, while <b><u>\"* *\"</u></b> will display any two words between quotes, etc."));
    setStr(SearchMethodInfo9_v1, QString("SearchMethodInfo9_v1"), QString("Тази опция указва дали да се прави разлика между главни и малки букви."), QString("Differentiate between upper and lower case."));
    setStr(SearchMethodInfo10_v1, QString("SearchMethodInfo10_v1"), QString("Тук не се търси във всеки стих, а във всяка глава. Например - търсим онзи стих, където някой от Апостолите говореше за вода и кръщение. Затова търсим двете думи: <b><u>вода кръщение</u></b>, но нито един стих няма такова съдържание. Причината е, че тези две думи са разположени в два съседни стиха на една глава. Ако маркираме опцията \"<i>Търси в глава</i>\", ще излязат няколко глави, в които се срещат тези две думи и веднага ще открием въпросните два стиха (1 Пет. 3:20,21)."), QString("Instead of searching in a verse it searches in a chapter. For instance, we need to find that one verse where on of the Apostols is talking about water and baptism. So we search for <b><u>water baptism</u></b>, but there are no matches. The reason behind this is that the two words are located in adjacent verses. If we select the option \"<i>Search in chapter</i>\", several matches will pop-up and we can immediately find the relevant verses (1Pet 3:20,21)."));
  strSettings->endGroup();
    
  strSettings->beginGroup(QString("Statistics"));
    setStr(TwoActiveBibleTextsNeeded_v1, QString("TwoActiveBibleTextsNeeded_v1"), QString("Трябва да са показани два Библейски текста и да не е режим на ежедневно четене."), QString("Two active Bible texts required. Daily reading mode must be disabled."));
    setStr(OneActiveBibleTextNeeded_v1, QString("OneActiveBibleTextNeeded_v1"), QString("Трябва да е показан само един Библейски текст."), QString("Only one active Bible text required."));
    setStr(Statistics_v1, QString("Statistics_v1"), QString("Статистика:"), QString("Statistics:"));
    setStr(MatchedWords_v1, QString("MatchedWords_v1"), QString("Съвпадащи думи:"), QString("Matched words:"));
    setStr(AllWords_v1, QString("AllWords_v1"), QString("Всички думи:"), QString("All Words:"));
    setStr(PercentageMatch_v1, QString("PercentageMatch_v1"), QString("Съвпадение:"), QString("Match percentage:"));
    setStr(UniqueWordsOnly_v1, QString("UniqueWordsOnly_v1"), QString("Уникални думи:"), QString("Unique Words:"));
    setStr(HapaxLegomenon_v1, QString("HapaxLegomenon_v1"), QString("Думи, които се срещат само веднъж (Hapax legomenon):"), QString("Words only found once (Hapax legomenon):"));
    setStr(SortByOccurrenceOrder_v1, QString("SortByOccurrenceOrder_v1"), QString("Сортиране по честота на срещане"), QString("Sort by frequency of occurrence"));
    setStr(SortByAlphabeticalOrder_v1, QString("SortByAlphabeticalOrder_v1"), QString("Сортиране по азбучен ред"), QString("Sort by alphabetical order")); 
  strSettings->endGroup();

  strSettings->beginGroup(QString("ExTextWindow"));
    setStr(Save_v1, QString("Save_v1"), QString("Записва"), QString("Save"));
    setStr(SaveChangesQuestion_v1, QString("SaveChangesQuestion_v1"), QString("Съдържанието е променено.\nДа се запишат ли промените?"), QString("The contents have been modified.\nDo you want to save your changes?")); // The document has been modified.
  strSettings->endGroup();

  strSettings->beginGroup(QString("FastAccessWidget"));
    setStr(FastAccess_v1, QString("FastAccess_v1"), QString("Бърз достъп"), QString("Fast Access"));
    setStr(ValidExpression_v1, QString("ValidExpression_v1"), QString("Валидно изписване"), QString("Valid Expression"));
  strSettings->endGroup();

  strSettings->beginGroup(QString("HttpAccess"));
    setStr(Connecting_v1, QString("Connecting_v1"), QString("Осъществява се връзка. Моля изчакайте..."), QString("Connecting... Please wait..."));
    setStr(ConnectingError_v1, QString("ConnectingError_v1"), QString("Има някакъв проблем с връзката. Може би не сте настроили проксито (ако има такова) или в момента няма връзка с Интернет."), QString("There has been a connection issue. If you are using a proxy it might not be configured, or there is no connection to the Internet."));
    setStr(Error_v1, QString("Error_v1"), QString("Грешка"), QString("Error"));
    setStr(OnlineMessages_v1, QString("OnlineMessages_v1"), QString("Online съобщения:"), QString("Online Messages:"));
    setStr(NoMessages_v1, QString("NoMessages_v1"), QString("Няма"), QString("No Messages"));
    setStr(InaccessibleInfo_v1, QString("InaccessibleInfo_v1"), QString("Информацията не може да бъде получена!"), QString("Data cannot be received!"));
    setStr(InaccessibleInfoFileError_v1, QString("InaccessibleInfoFileError_v1"), QString("Информацията не може да бъде прочетена! Открита е грешка във файла."), QString("Data cannot be read! File error."));
    setStr(CheckNewAppVersionOnWEB_v1, QString("CheckNewAppVersionOnWEB_v1"), QString("Проверете дали има по-нова версия на страницата на MatCrossBible:"), QString("Check for a newer version on the MatCrossBible web page:"));
    setStr(CurrentVersion_v1, QString("CurrentVersion_v1"), QString("Текуща версия"), QString("Current version"));
    setStr(LastReleaseVersion_v1, QString("LastReleaseVersion_v1"), QString("Последна реализирана версия"), QString("Last release version"));
    setStr(HasNewReleaseVersion_v1, QString("HasNewReleaseVersion_v1"), QString("ИМА ПО-НОВА РЕАЛИЗИРАНА ВЕРСИЯ"), QString("NEW RELEASE VERSION AVAILABLE"));
    setStr(NoNewReleaseVersion_v1, QString("NoNewReleaseVersion_v1"), QString("НЯМА ПО-НОВА РЕАЛИЗИРАНА ВЕРСИЯ"), QString("NO NEW RELEASE VERSION AVAILABLE"));
    setStr(DownloadNewAppVerFromWEB_v1, QString("DownloadNewAppVerFromWEB_v1"), QString("Новата версия можете да свалите от Интернет страницата на MatCrossBible:"), QString("You can download the new version from the internet web page of MatCrossBible:"));

    setStr(Download_v1, QString("Download_v1"), QString("Изтегляне"), QString("Download"));
    setStr(DownloadStop_v1, QString("DownloadStop_v1"), QString("Прекратяване"), QString("Stop")); // Terminate, Break
    setStr(DownloadDone_v1, QString("DownloadDone_v1"), QString("Изтеглянето завърши"), QString("Download Complete"));
    setStr(DownloadDoneNeedToResraer_v1, QString("DownloadDoneNeedToResraer_v1"), QString("Изтеглянето завърши. Трябва да рестартирате MatCrossBible."), QString("Download complete. You must restart MatCrossBible."));
    setStr(DownloadFailure_v1, QString("DownloadFailure_v1"), QString("Изтеглянето пропадна."), QString("Download failed."));
    setStr(FileDataError_v1, QString("FileDataError_v1"), QString("Най-вероятно файлът е повреден или непълен."), QString("File is damaged or incomplete."));
    setStr(DownloadTextInfo1_v1, QString("DownloadTextInfo1_v1"), QString("Щракнете върху желания текст за да го прибавите към MatCrossBible."), QString("Click on the desired text to add it to MatCrossBible."));
    setStr(DownloadTextInfo2_v1, QString("DownloadTextInfo2_v1"), QString("Текстовете в зелен цвят са вече налични в MatCrossBible. Наличен текст може да бъде изтрит само чрез ръчно изтриване на файла при спряна програма."), QString("Text in green are already available in MatCrossBible. Downloaded text can only be removed through manual deletion of the file when the App is closed."));
    setStr(DownloadTextInfo3_v1, QString("DownloadTextInfo3_v1"), QString("Текстовете, за които се очаква разрешение за ползване не могат да бъдат изтеглени на този етап."), QString("Texts awaiting permission cannot be downloaded at this stage."));
    setStr(Language_v1, QString("Language_v1"), QString("Език"), QString("Language"));
    setStr(Text_v1, QString("Text_v1"), QString("Текст"), QString("Text"));
    setStr(ShortDescription_v1, QString("ShortDescription_v1"), QString("Кратко описание"), QString("Short Description"));
    setStr(File_v1, QString("File_v1"), QString("Файл"), QString("File"));
    setStr(Note_v1, QString("Note_v1"), QString("Забележка"), QString("Note"));
    setStr(Available_v1, QString("Available_v1"), QString("Наличен"), QString("Available"));
    setStr(ExpectRightToUse_v1, QString("ExpectRightToUse_v1"), QString("Очаква се разрешение за ползване"), QString("Awaiting permission"));
    setStr(DownloadFailureInvalidLink_v1, QString("DownloadFailureInvalidLink_v1"), QString("Файлът, който искате не може да бъде изтеглен! Невалиден линк:"), QString("The file cannot be downloaded! Invalid link:"));
    setStr(AlternativeDownload_v1, QString("AlternativeDownload_v1"), QString("За сваляне на допълнителни файлове прочетете долните инструкции."), QString("To download additional files read the instructions below."));
    setStr(GetMoreBibleTextsInfo1_v1, QString("GetMoreBibleTextsInfo1_v1"), QString("В момента разполагате със следните текстове:"), QString("Currently you have the following texts available:"));
    setStr(GetMoreBibleTextsInfo2_v1, QString("GetMoreBibleTextsInfo2_v1"), QString("В момента не разполагате с никакви текстове!"), QString("Currently you have no Bible texts!"));
    setStr(GetMoreBibleTextsInfo3_v1, QString("GetMoreBibleTextsInfo3_v1"), QString("Можете да свалите допълнителни текстове на Библията за MatCrossBible от Интернет."), QString("You can download additional Bible texts for MatCrossBible from the Internet."));
    setStr(GetMoreBibleTextsInfo4_v1, QString("GetMoreBibleTextsInfo4_v1"), QString("Трябва да свалите текстове на Библията за MatCrossBible от Интернет."), QString("You must download any additional Bible texts for MatCrossBible from the Internet."));
    setStr(GetMoreBibleTextsInfo5_v1, QString("GetMoreBibleTextsInfo5_v1"), QString("За целта посетете страницата 'Библейски текстове' на MatCrossBible:"), QString("Visit the 'Bible texts' page of MatCrossBible:"));
    setStr(GetMoreBibleTextsInfo6_v1, QString("GetMoreBibleTextsInfo6_v1"), QString("Всеки текст (превод/ревизия) представлява един единствен файл."), QString("Each text (translation/revision) consists of one file."));
    setStr(GetMoreBibleTextsInfo7_v1, QString("GetMoreBibleTextsInfo7_v1"), QString("Всичко, което трябва да направите, е да свалите желания файл и да го запишете в директория:"), QString("All you must do is download the desired file and save it to folder:")); // Този текст е същият като текста десетина реда по-долу.
    setStr(GetMoreBibleTextsInfo8_v1, QString("GetMoreBibleTextsInfo8_v1"), QString("При следващо пускане на MatCrossBible, новият текст ще се добави автоматично в панела с текстовете."), QString("Next time you open MatCrossBible, the new text will be added automatically to the panel."));

    setStr(MoreTRFiles_v1, QString("MoreTRFiles_v1"), QString("Други TR файлове"), QString("More TR Files"));
    setStr(DownloadTRFilesInfo1_v1, QString("DownloadTRFilesInfo1_v1"), QString("Щракнете върху желания TR файл за да го прибавите към MatCrossBible."), QString("Click on the desired TR file to add it to MatCrossBible."));
    setStr(DownloadTRFilesInfo2_v1, QString("DownloadTRFilesInfo2_v1"), QString("Файловете в зелен цвят са вече налични в MatCrossBible. Наличен TR файл може да бъде изтрит само чрез ръчно изтриване на файла."), QString("Files in green are already available in MatCrossBible. Downloaded TR file can only be removed by manually deleting the file."));
    setStr(PartialTranslated_v1, QString("PartialTranslated_v1"), QString("Частично преведен"), QString("Partially translated"));
    setStr(Translator_v1, QString("Translator_v1"), QString("Преводач"), QString("Translator"));
    setStr(LastModify_v1, QString("LastModify_v1"), QString("Последна промяна"), QString("Last Change"));
    setStr(GetMoreTRFilesInfo1_v1, QString("GetMoreTRFilesInfo1_v1"), QString("В момента разполагате със следните TR файлове:"), QString("Currently you have the following TR files available:"));
    setStr(GetMoreTRFilesInfo2_v1, QString("GetMoreTRFilesInfo2_v1"), QString("Можете да свалите допълнителни TR файлове за MatCrossBible от Интернет."), QString("You can download additional TR files for MatCrossBible from the Internet."));
    setStr(GetMoreTRFilesInfo3_v1, QString("GetMoreTRFilesInfo3_v1"), QString("За целта посетете страницата:"), QString("Visit the web page:"));
    setStr(GetMoreTRFilesInfo4_v1, QString("GetMoreTRFilesInfo4_v1"), QString("Всичко, което трябва да направите, е да свалите желания файл и да го запишете в директория:"), QString("All you have to do is download the desired file and save it to folder:"));
    setStr(GetMoreTRFilesInfo5_v1, QString("GetMoreTRFilesInfo5_v1"), QString("При следващо пускане на MatCrossBible ще можете да изберете новия TR файл."), QString("Next time you start MatCrossBible you will be able to select the new TR file."));
  strSettings->endGroup();

  strSettings->beginGroup(QString("WWWResources"));
    setStr(AddLink_v1, QString("AddLink_v1"), QString("Добавяне"), QString("Add"));
    setStr(EditDelLink_v1, QString("EditDelLink_v1"), QString("Редактиране/Изтриване"), QString("Edit/Delete"));
    setStr(URL_v1, QString("URL_v1"), QString("URL:"), QString("URL:"));
    setStr(Description_v1, QString("Description_v1"), QString("Описание:"), QString("Description:"));
    setStr(InsertLinkRow_v1, QString("InsertLinkRow_v1"), QString("Вмъква този ред под избрания номер"), QString("Insert this row below the chosen number"));
    setStr(DeleteLinkRow_v1, QString("DeleteLinkRow_v1"), QString("Изтрива този ред"), QString("Delete row"));
    setStr(FileReadError_v1, QString("FileReadError_v1"), QString("Грешка при четене от файла!"), QString("Error, file cannot be read!"));
    setStr(Row_v1, QString("Row_v1"), QString("Ред"), QString("Row"));
    setStr(EditLinksInfo1_v1, QString("EditLinksInfo1_v1"), QString("Можете да въведете нов линк към страница в Интернет."), QString("You can add a new web page link."));
    setStr(EditLinksInfo2_v1, QString("EditLinksInfo2_v1"), QString("Можете да редактирате или изтриете съществуващ линк (ред)."), QString("You can edit or delete an existing link (row)."));
    setStr(EditLinksInfo3_v1, QString("EditLinksInfo3_v1"), QString("Ако при редактиране или въвеждане на нов линк (ред) <br>оставите празно полето 'URL' и напишете текст само в <br>полето 'Описание', то този текст ще се изпише с оранжев цвят <br>и ще служи като заглавно име на група линкове."), QString("If you add or edit a link (row) by leaving the 'URL' <br>field empty and only fill in the 'Description' field, <br>the text will appear in orange and will serve <br>as a title to a group of links."));
    setStr(EditLinksInfo4_v1, QString("EditLinksInfo4_v1"), QString("Ако оставите празни и двете полета ще се появи празен ред,<br>който ще служи като разделител между линковете."), QString("Leaving both fields empty will create an empty line,<br>which will serve as a separator."));
    setStr(EditLinksInfo5_v1, QString("EditLinksInfo5_v1"), QString("По този начин можете да си сортиране линковете по категории."), QString("You can thus sort links in categories."));
  strSettings->endGroup();

  strSettings->beginGroup(QString("MainWindow"));
    setStr(MainWindow_v1, QString("MainWindow_v1"), QString("Основен прозорец"), QString("Main Window"));
    setStr(CurrentView_v1, QString("CurrentView_v1"), QString("Текущ изглед"), QString("Current View (Dock Window)"));
    setStr(ToolbarPanels_v1, QString("ToolbarPanels_v1"), QString("Панели с инструменти"), QString("Toolbar Panels"));
    setStr(BibleTextsFileProblem1_v1, QString("BibleTextsFileProblem1_v1"), QString("Не са открити файлове с текстове на Библията!"), QString("No Bible text files have been found!"));
    setStr(BibleTextsFileProblem2_v1, QString("BibleTextsFileProblem2_v1"), QString("Файловете трябва да са с разширение <b>.hbt</b> и да са в директория:"), QString("Files must have <b>.hbt</b> extension and be in the following folder:"));
    setStr(BibleTextsFileProblem3_v1, QString("BibleTextsFileProblem3_v1"), QString("Възможни причини са:<br>- няма такива файлове;<br>- наличните файлове използват структура различна от очакваната версия;<br>- файловете са повредени или е нарушена тяхната структура."), QString("Possible reasons:<br>- no such files;<br>- available files use a different structure version;<br>- files are corrupted, or their structure is damaged."));
    setStr(NoOpenText1_v1, QString("NoOpenText1_v1"), QString("Няма отворен текст"), QString("No Open Text"));
    setStr(NoOpenText2_v1, QString("NoOpenText2_v1"), QString("Няма избран текст на Библията!"), QString("No Bible text selected!"));
    setStr(NoOpenText3_v1, QString("NoOpenText3_v1"), QString("Изберете текст от панела с наличните текстове.<br>От същия панел можете да отворите формата за изтегляне на други текстове от Интернет или да пренаредите съществуващите."), QString("Choose a text from the panel with available texts.<br>Using the same panel you can download new texts, or rearrange existing ones."));
    setStr(NoOpenText4_v1, QString("NoOpenText4_v1"), QString("Налични са следните текстове:"), QString("The following texts are available:"));
    setStr(AboutMatCrossBible1_v1, QString("AboutMatCrossBible1_v1"), QString("MatCrossBible (старо име CrossBgBible) е защитена с GPL лиценз."), QString("MatCrossBible (previously CrossBgBible) is protected by GPL license."));
    setStr(AboutMatCrossBible2_v1, QString("AboutMatCrossBible2_v1"), QString("Разпространява се напълно свободно и безплатно!"), QString("Distributed completely free!"));
    setStr(AboutMatCrossBible3_v1, QString("AboutMatCrossBible3_v1"), QString("За създаването й се използва свободен, безплатен софтуер (Qt SDK, Inkscape, GIMP, Linux)."), QString("For its creation has been used only freely available, freeware software (Qt SDK, Inkscape, GIMP, Linux)."));
    setStr(AboutMatCrossBible4_v1, QString("AboutMatCrossBible4_v1"), QString("MatCrossBible e базирана на Qt C++ библиотеката и работи еднакво на всяка операционна система поддържаща Qt. Най-популярните операционни системи поддържащи Qt са: Windows, Linux, BSD, MAC."), QString("MatCrossBible is based on the Qt C++ and performs equaly well on any operation system that supports Qt. Most popular operating systems are: Windows, Linux, BSD, MAC."));
    setStr(Open_v1, QString("Open_v1"), QString("Отваря програмата"), QString("Open"));
    setStr(RestartNowQuestion_v1, QString("RestartNowQuestion_v1"), QString("Да се рестартира ли програмата сега?"), QString("Do you wish to restart the App now?"));
    setStr(TitleBarButtons_v1, QString("TitleBarButtons_v1"), QString("Бутони на прозорците и панелите с инструменти"), QString("Buttons on the windows and tool panels"));
  strSettings->endGroup();

  strSettings->beginGroup(QString("TextView"));
    setStr(SearchTextInTheBible_v1, QString("SearchTextInTheBible_v1"), QString("Търси селектирания текст в Библията"), QString("Search selected text in the Bible"));
    setStr(CustomHighlightAdd_v1, QString("CustomHighlightAdd_v1"), QString("Оцветява селектирания текст"), QString("Highlight selected text"));
    setStr(CustomHighlightDel_v1, QString("CustomHighlightDel_v1"), QString("Премахва оцветяването"), QString("Remove highlight"));
    setStr(TextNotFound_v1, QString("TextNotFound_v1"), QString("Търсеният текст не е открит!"), QString("No matches!"));
    setStr(MatchesToOccurrences_v1, QString("MatchesToOccurrences_v1"), QString("Съвпадения със селектирания текст:"), QString("Match(es) to occurrence(s):"));
    setStr(ShowTextError_v1, QString("ShowTextError_v1"), QString("Грешка при показване на текста!<br>Има нарушение в структурата на файла."), QString("Text display error!<br>File structure has been damaged."));
    setStr(CreateHTMLMatCrossBibleV1_v1, QString("CreateHTMLMatCrossBibleV1_v1"), QString("Създаване на HTML MatCrossBible V1"), QString("Create HTML MatCrossBible V1"));
    setStr(CreateHTMLMatCrossBibleV2_v1, QString("CreateHTMLMatCrossBibleV2_v1"), QString("Създаване на HTML MatCrossBible V2"), QString("Create HTML MatCrossBible V2"));
    setStr(HTMLMatCrossBibleCreatedIn_v1, QString("HTMLMatCrossBibleCreatedIn_v1"), QString("HTML MatCrossBible е създадена в директория:"), QString("HTML MatCrossBible has been created in folder:"));
  strSettings->endGroup();

  strSettings->beginGroup(QString("DictionaryCommentary"));
    setStr(Back_v1, QString("Back_v1"), QString("Назад"), QString("Back"));
    setStr(Forward_v1, QString("Forward_v1"), QString("Напред"), QString("Forward"));
    setStr(PreviousGroup_v1, QString("PreviousGroup_v1"), QString("Предходна група"), QString("Previous Group"));
    setStr(NextGroup_v1, QString("NextGroup_v1"), QString("Следваща група"), QString("Next Group"));
    setStr(CatchCopyEvent_v1, QString("CatchCopyEvent_v1"), QString("Прихваща копиране на текста в клипборда"), QString("Catch copy event"));
    setStr(CatchSelectEvent_v1, QString("CatchSelectEvent_v1"), QString("Прихваща селектиране само при натиснат клавиш Alt"), QString("Catch select event only if the Alt key is pressed"));
    setStr(ChooseDictionaryOrCommentary_v1, QString("ChooseDictionaryOrCommentary_v1"), QString("Изберете речник или коментар"), QString("Choose dictionary or commentary"));
    setStr(DictionariesAndCommentaries_v1, QString("DictionariesAndCommentaries_v1"), QString("Речници и коментари"), QString("Dictionaries and commentaries"));
    setStr(NoFoundDictsOrComms_v1, QString("NoFoundDictsOrComms_v1"), QString("Няма открити речници или коментари в директория:"), QString("No dictionaries or commentaries in folder:")); // No found dictionaries or commentaries in folder:
    setStr(PossibleDifferentVerseNumber_v1, QString("PossibleDifferentVerseNumber_v1"), QString("Номера на стиха показан тук се изчислява според глобалната структура и може да не отговаря на действителния"), QString("The verse number displayed here is calculated using the global structure and might not match the actual one"));
    setStr(Version_v1, QString("Version_v1"), QString("Версия:"), QString("Version:"));
    setStr(Author_v1, QString("Author_v1"), QString("Автор:"), QString("Author:"));
    setStr(FileName_v1, QString("FileName_v1"), QString("Име на файла:"), QString("File name:"));
    setStr(AllWordsPhrases_v1, QString("AllWordsPhrases_v1"), QString("Всички думи/фрази:"), QString("All words/phrases:"));
    setStr(AllCommentary_v1, QString("AllCommentary_v1"), QString("Всички коментари:"), QString("All commentary:"));
    setStr(IncorrectHeaderSection_v1, QString("IncorrectHeaderSection_v1"), QString("Грешка! Некоректна начална секция във файла:"), QString("Error! Incorrect header section in file:"));
    setStr(IncorrectDataSection_v1, QString("IncorrectDataSection_v1"), QString("Грешка! Некоректна секция с данни във файла:"), QString("Error! Incorrect data section in file:"));
    setStr(EqualWordsExpressions_v1, QString("EqualWordsExpressions_v1"), QString("Некоректни данни - има повтарящи се думи/изрази:"), QString("Incorrect data - there are repeating words/expressions:")); // equal (равностойни) or repeating (повтарящи се)?
  strSettings->endGroup();

  strSettings->beginGroup(QString("Settings"));
    setStr(TabLanguage_v1, QString("TabLanguage_v1"), QString("Език"), QString("Language"));
    setStr(TabColors_v1, QString("TabColors_v1"), QString("Цветове"), QString("Colors"));
    setStr(TabView_v1, QString("TabView_v1"), QString("Изглед"), QString("View"));
    setStr(TabText_v1, QString("TabText_v1"), QString("Текст"), QString("Text"));
    setStr(TabSearch_v1, QString("TabSearch_v1"), QString("Търсене"), QString("Search"));
    setStr(TabAudio_v1, QString("TabAudio_v1"), QString("Аудио"), QString("Audio"));
    setStr(TabMisc_v1, QString("TabMisc_v1"), QString("Други"), QString("Misc"));
    setStr(EffectAfterChange_v1, QString("EffectAfterChange_v1"), QString("Някои от направените промени ще влезнат в сила след действие, свързано с конкретната настройка!"), QString("Some of the performed changes will only take effect after an action related to the particular setting!"));
    setStr(EffectAfterRestart_v1, QString("EffectAfterRestart_v1"), QString("Някои от направените промени ще влезнат в сила след рестартиране на програмата!"), QString("Some of the performed changes will only take effect after App restart!"));
    setStr(EffectAfterChangeOrRestart_v1, QString("EffectAfterChangeOrRestart_v1"), QString("Някои от направените промени ще влезнат в сила след действие, свързано с конкретната настройка, а други след рестартиране на програмата!"), QString("Some of the performed changes will only take effect after an action related to the particular setting, while others after App restart!"));
    setStr(GetDefaultSettings_v1, QString("GetDefaultSettings_v1"), QString("Първоначални настройки"), QString("Restore Default Settings"));
    setStr(GetDefaultSettingsQuestion_v1, QString("GetDefaultSettingsQuestion_v1"), QString("Да бъдат ли възстановени първоначално заложените настройки?"), QString("Are you sure you want to restore default settings?"));
    setStr(PositionTop_v1, QString("PositionTop_v1"), QString("Позиция горе"), QString("Position Top"));
    setStr(PositionBottom_v1, QString("PositionBottom_v1"), QString("Позиция долу"), QString("Position Bottom"));
    setStr(PositionLeft_v1, QString("PositionLeft_v1"), QString("Позиция ляво"), QString("Position Left"));
    setStr(PositionRight_v1, QString("PositionRight_v1"), QString("Позиция дясно"), QString("Position Right"));
    setStr(WhiteTheme_v1, QString("WhiteTheme_v1"), QString("Бяла тема"), QString("White theme"));
    setStr(GreyTheme_v1, QString("GreyTheme_v1"), QString("Сива тема"), QString("Grey theme"));
    setStr(DarkTheme_v1, QString("DarkTheme_v1"), QString("Тъмна тема"), QString("Dark theme"));

    setStr(TCDock1TextColorF_v1, QString("TCDock1TextColorF_v1"), QString("Цвят на текста в стандартен раздел"), QString("Text color in standard dock window"));
    setStr(TCDock1TextColorB_v1, QString("TCDock1TextColorB_v1"), QString("Цвят на фона в стандартен раздел"), QString("Background color in standard dock window"));
    setStr(TCDock2TextColorF_v1, QString("TCDock2TextColorF_v1"), QString("Цвят на текста в специализиран раздел/панел"), QString("Text color in special window/panel"));
    setStr(TCDock2TextColorB_v1, QString("TCDock2TextColorB_v1"), QString("Цвят на фона в специализиран раздел/панел"), QString("Background color in special window/panel"));
    setStr(TCDockBGImage_v1, QString("TCDockBGImage_v1"), QString("Картинка"), QString("Image"));
    setStr(TCDockBGImageTT_v1, QString("TCDockBGImageTT_v1"), QString("Картинка за фон на раздела"), QString("Background image"));
    setStr(TCOldTestamentColorF_v1, QString("TCOldTestamentColorF_v1"), QString("Цвят на имената на книгите в Стария Завет"), QString("Color of the titles of the Old Testament books"));
    setStr(TCOldTestamentAlphaFTT_v1, QString("TCOldTestamentAlphaFTT_v1"), QString("Степен на полупрозрачност на този цвят. Използва се за фонов цвят на неща, свързани със Стария Завет"), QString("Color transparency. Used as background color for Old Testament related things"));
    setStr(TCNewTestamentColorF_v1, QString("TCNewTestamentColorF_v1"), QString("Цвят на имената на книгите в Новия Завет"), QString("Color of the titles of the New Testament books"));
    setStr(TCNewTestamentAlphaFTT_v1, QString("TCNewTestamentAlphaFTT_v1"), QString("Степен на полупрозрачност на този цвят. Използва се за фонов цвят на неща, свързани с Новия Завет"), QString("Color transparency. Used as background color for New Testament related things"));
    setStr(TCTextInBracketsColorF_v1, QString("TCTextInBracketsColorF_v1"), QString("Цвят на текста в {} скоби"), QString("Color of text in {} brackets"));
    setStr(TCJesusWordsColorF_v1, QString("TCJesusWordsColorF_v1"), QString("Цвят на думите на Господ Исус Христос"), QString("Color of the Words of Lord Jesus Christ"));
    setStr(TCCompareEqColorF_v1, QString("TCCompareEqColorF_v1"), QString("Цвят на еднаквите думи в режим на сравняване"), QString("Matching words color in compare mode"));
    setStr(TCCompareNoEqColorF_v1, QString("TCCompareNoEqColorF_v1"), QString("Цвят на различните думи в режим на сравняване"), QString("Different words color in compare mode"));
    setStr(TCAppColorF_v1, QString("TCAppColorF_v1"), QString("Цвят на прозорците и панелите с инструменти"), QString("Windows and toolbars color"));
    setStr(TCAppColorB_v1, QString("TCAppColorB_v1"), QString("Цвят на фона на прозорците и панелите с инструменти"), QString("Windows and toolbars background color"));
    setStr(TCShow3DTitleBarTT_v1, QString("TCShow3DTitleBarTT_v1"), QString("Показва заглавните ленти на панелите с инструменти изпъкнали (3D ефект). Ефектът не се вижда при светли панели."), QString("Add 3D effect to the title bars of the tool panels. The effect is not visible on bright panels."));
    setStr(TCInfo_v1, QString("TCInfo_v1"), QString("* Повечето от цветовете се използват и на други места в програмата"), QString("* Most colors are used in other places too"));

    setStr(TVDocks_v1, QString("TVDocks_v1"), QString("Раздели"), QString("Docks"));
    setStr(TVTMenu_v1, QString("TVTMenu_v1"), QString("Главна лента с инструменти"), QString("Main toolbar"));
    setStr(TVFontSize_v1, QString("TVFontSize_v1"), QString("Големина на шрифта"), QString("Font Size"));
    setStr(TVTMenuIconSize_v1, QString("TVTMenuIconSize_v1"), QString("Размер на иконите"), QString("Icon Size"));
    setStr(TVTMenuAutoIconColor_v1, QString("TVTMenuAutoIconColor_v1"), QString("Автоматично генериран цвят на иконите"), QString("Automatically generated icon color"));
    setStr(TVBooksToolBar_v1, QString("TVBooksToolBar_v1"), QString("Панел с книгите и отметките"), QString("Books and bookmarks Toolbar"));
    setStr(TVSearchToolBar_v1, QString("TVSearchToolBar_v1"), QString("Панел с инструменти за търсене в Библията"), QString("Bible search Toolbar"));
    setStr(TVSearchToolBarWidth_v1, QString("TVSearchToolBarWidth_v1"), QString("Широчина на панела"), QString("Toolbar width"));
    setStr(TVProjectorToolBar_v1, QString("TVProjectorToolBar_v1"), QString("Панел с инструменти за проектора"), QString("Projector Toolbar"));
    setStr(TVProjectorPrevScreenWidth_v1, QString("TVProjectorPrevScreenWidth_v1"), QString("Големина (широчина) на малкия екран на проектора"), QString("Projector preview screen width"));

    setStr(TTGlobalFontSize_v1, QString("TTGlobalFontSize_v1"), QString("Големина на шрифта за цялото приложение:"), QString("Global font size:"));
    setStr(TTGlobalFontSizeTT_v1, QString("TTGlobalFontSizeTT_v1"), QString("Големина на шрифта за цялото приложение (менюта, подсказки и всичко, за което не е указана друга големина на шрифта)"), QString("Font size for the whole application (menus, hints and everything else that is not separately configured)"));
    setStr(TTAntialias_v1, QString("TTAntialias_v1"), QString("Antialias"), QString("Antialias"));
    setStr(TTTheHolyTextFont_v1, QString("TTTheHolyTextFont_v1"), QString("Шрифт на Библейския текст"), QString("The Holy Text Font"));
    setStr(TTVerseNumberBold_v1, QString("TTVerseNumberBold_v1"), QString("Удебелен шрифт на номерата на стиховете"), QString("Verse number bold font"));
    setStr(TTVerseNumberSup_v1, QString("TTVerseNumberSup_v1"), QString("Умален шрифт на номерата на стиховете"), QString("Verse number small size font"));
    setStr(TTTheHolyTextFeatures_v1, QString("TTTheHolyTextFeatures_v1"), QString("Особености на Библейския текст"), QString("The Holy Text Features"));
    setStr(TTVerseStruct_v1, QString("TTVerseStruct_v1"), QString("Начин на изписване на стиховете"), QString("Verse display mode"));
    setStr(TTNumeration1_v1, QString("TTNumeration1_v1"), QString("Западна номерация на книгата Псалми"), QString("Western numeration of Psalms"));
    setStr(TTNumeration2_v1, QString("TTNumeration2_v1"), QString("Източна номерация на книгата Псалми"), QString("Eastern numeration of Psalms"));
    setStr(TTNumerationTT_v1, QString("TTNumerationTT_v1"), QString("Указва коя да бъде подразбиращата се номерация при показване на два и повече текста с различни номерации на стиховете (разликите са само в Псалми - от Псалм 9 до Псалм 147)"), QString("Choose default numeration when displaying texts with different verse numerations. The differences are only from Psalm 9 to 147."));
    setStr(TTBooksOrder1_v1, QString("TTBooksOrder1_v1"), QString("ДА-Рим-1Кор...Евр-Яков-1Пет...Юда-Откр"), QString("Acts-Rom-1Cor...Heb-James-1Pet...Jude-Rev"));
    setStr(TTBooksOrder2_v1, QString("TTBooksOrder2_v1"), QString("ДА-Яков-1Пет...Юда-Рим-1Кор...Евр-Откр"), QString("Acts-James-1Pet...Jude-Rom-1Cor...Heb-Rev"));
    setStr(TTBooksOrderTT_v1, QString("TTBooksOrderTT_v1"), QString("Указва подредбата (реда) на книгите в Новия Завет"), QString("Choose New Testament books order"));
    setStr(TTShowDeuterocanonical_v1, QString("TTShowDeuterocanonical_v1"), QString("Показва Второканоничните книги"), QString("Show Deuterocanonical books"));
    setStr(TTShowAbsVerseNumber_v1, QString("TTShowAbsVerseNumber_v1"), QString("Показва глобален (абсолютен) номер на стих"), QString("Show Absolute Verse Number"));

    setStr(TSFoundWordsFormat_v1, QString("TSFoundWordsFormat_v1"), QString("Формат на търсените думи при търсене в Библията"), QString("Bible search words formatting"));
    setStr(TSWordsFormatBold_v1, QString("TSWordsFormatBold_v1"), QString("Удебеляване на думите"), QString("Words bold font"));
    setStr(TSWordsFormatUnderline_v1, QString("TSWordsFormatUnderline_v1"), QString("Подчертаване на думите"), QString("Underline words"));
    setStr(TSWordsFormatColorF_v1, QString("TSWordsFormatColorF_v1"), QString("Оцветяване на думите със следните цветове:"), QString("Color the words with the following colors:"));
    setStr(TSWordsFormatColorFTT_v1, QString("TSWordsFormatColorFTT_v1"), QString("Всяка една от търсените думи се оцветява в различен цвят.\nАко се търсят повече от пет думи, то цветовете се повтарят."), QString("Each searched word is colored differently.\nIf more than five words are searched, the colors repeat."));
    setStr(TSWordsFormatColor1F_v1, QString("TSWordsFormatColor1F_v1"), QString("Цвят на първата, шестата и т.н. търсени думи"), QString("Color for the first, sixth, etc. words"));
    setStr(TSWordsFormatColor2F_v1, QString("TSWordsFormatColor2F_v1"), QString("Цвят на втората, седмата и т.н. търсени думи"), QString("Color for the second, seventh, etc. words"));
    setStr(TSWordsFormatColor3F_v1, QString("TSWordsFormatColor3F_v1"), QString("Цвят на третата, осмата и т.н. търсени думи"), QString("Color for the third, eighth, etc. words"));
    setStr(TSWordsFormatColor4F_v1, QString("TSWordsFormatColor4F_v1"), QString("Цвят на четвъртата, деветата и т.н. търсени думи"), QString("Color for the fourth, ninth, etc. words"));
    setStr(TSWordsFormatColor5F_v1, QString("TSWordsFormatColor5F_v1"), QString("Цвят на петата, десетата и т.н. търсени думи"), QString("Color for the fifth, tenth, etc. words"));
    setStr(TSWordsFormatColorB_v1, QString("TSWordsFormatColorB_v1"), QString("Оцветяване на фона на думите със следните цветове:"), QString("Higlight the words with the following colors:"));
    setStr(TSWordsFormatColorBTT_v1, QString("TSWordsFormatColorBTT_v1"), QString("Фонът на всяка една от търсените думи се оцветява в различен цвят.\nАко се търсят повече от пет думи, то цветовете се повтарят."), QString("Each searched word is highlighted with a different (background) color.\nIf more than five words are searched, the colors repeat."));
    setStr(TSWordsFormatColor1B_v1, QString("TSWordsFormatColor1B_v1"), QString("Цвят на фона на първата, шестата и т.н. търсени думи"), QString("Background color for the first, sixth, etc. words"));
    setStr(TSWordsFormatColor2B_v1, QString("TSWordsFormatColor2B_v1"), QString("Цвят на фона на втората, седмата и т.н. търсени думи"), QString("Background color for the second, seventh, etc. words"));
    setStr(TSWordsFormatColor3B_v1, QString("TSWordsFormatColor3B_v1"), QString("Цвят на фона на третата, осмата и т.н. търсени думи"), QString("Background color for the third, eighth, etc. words"));
    setStr(TSWordsFormatColor4B_v1, QString("TSWordsFormatColor4B_v1"), QString("Цвят на фона на четвъртата, деветата и т.н. търсени думи"), QString("Background color for the fourth, ninth, etc. words"));
    setStr(TSWordsFormatColor5B_v1, QString("TSWordsFormatColor5B_v1"), QString("Цвят на фона на петата, десетата и т.н. търсени думи"), QString("Background color for the fifth, tenth, etc. words"));
    setStr(TSExtraSelectionColor_v1, QString("TSExtraSelectionColor_v1"), QString("Цвят на текста съвпадащ със селектирания текст"), QString("Color of text matching with selected text"));
    setStr(TSExtraSelectionColor1B_v1, QString("TSExtraSelectionColor1B_v1"), QString("Фонов цвят на текста съвпадащ със селектирания текст, селектиран чрез мишката"), QString("Background color of the text matching the selected text, selected by the mouse"));
    setStr(TSExtraSelectionColor2B_v1, QString("TSExtraSelectionColor2B_v1"), QString("Фонов цвят на текста съвпадащ със селектирания текст, селектиран чрез контекстното меню"), QString("Background color of the text matching the selected text, selected by the context menu"));

    setStr(TOOpenTheFolder_v1, QString("TOOpenTheFolder_v1"), QString("Отвори папката"), QString("Open  folder"));
    setStr(TOChoiceFolder_v1, QString("TOChoiceFolder_v1"), QString("Избери папка"), QString("Choose folder"));
    setStr(TOFirstIniPath_v1, QString("TOFirstIniPath_v1"), QString("Къде да се записват настройките, отметките, съдържанието на бележника и ресурсите на MatCrossBible?"), QString("Select where to save settings, bookmarks, pad contents and resources for MatCrossBible"));
    setStr(TOFirstIniPathH1_v1, QString("TOFirstIniPathH1_v1"), QString("В домашната директория на компютъра (препоръчително)"), QString("In PC home folder (recommended)"));
    setStr(TOFirstIniPathH2_v1, QString("TOFirstIniPathH2_v1"), QString("ПРЕДИМСТВА: При инсталиране на нова версия, настройките, отметките, съдържанието на бележника и ресурсите ще бъдат запазени."), QString("ADVANTAGES: When installing a new version all settings, bookmarks, pad contents and resources will be preserved."));
    setStr(TOFirstIniPathH3_v1, QString("TOFirstIniPathH3_v1"), QString("НЕДОСТАТЪЦИ: Програмата оставя следи от съществуването си на компютъра Ви (долупосочената директория)."), QString("DISADVANTAGES: The App leaves traces of its existance on your PC in the indicated folder."));
    setStr(TOFirstIniPathH4_v1, QString("TOFirstIniPathH4_v1"), QString("В домашната директория"), QString("Home folder"));
    setStr(TOFirstIniPathL1_v1, QString("TOFirstIniPathL1_v1"), QString("В локалната директория на изпълнимия файл (за преносима програма - portable)"), QString("In local folder of the executable file (for portable App)"));
    setStr(TOFirstIniPathL2_v1, QString("TOFirstIniPathL2_v1"), QString("ПРЕДИМСТВА: Може да бъде качена и стартирана от флашка, без да оставя следи на компютъра (всички настройки се записват на флашката)."), QString("ADVANTAGES: Can be installed and executed from a flash drive without leaving any traces on your PC (all settings are saved on the flash drive)."));
    setStr(TOFirstIniPathL3_v1, QString("TOFirstIniPathL3_v1"), QString("НЕДОСТАТЪЦИ: При инсталиране на нова версия, настройките, отметките, съдържанието на бележника и ресурсите могат да бъдат неволно изтрити заедно със старата програма."), QString("DISADVANTAGES: When installing a new version all settings, bookmarks, pad contents and resources could be involutarily deleted along with the old App."));
    setStr(TOFirstIniPathL4_v1, QString("TOFirstIniPathL4_v1"), QString("В локалната директория"), QString("Local folder"));
    setStr(TOIniPath_v1, QString("TOIniPath_v1"), QString("Път до конфигурационния файл, бележника и ресурсите"), QString("Path to the configuration file, the pad and the resources"));
    setStr(TOIniPathHome_v1, QString("TOIniPathHome_v1"), QString("Домашната директория на компютъра:"), QString("Computer's Home folder:"));
    setStr(TOIniPathLocal_v1, QString("TOIniPathLocal_v1"), QString("Локалната директория (за преносима програма - portable):"), QString("Local folder (for portable program):"));
    setStr(TOIniPathOther_v1, QString("TOIniPathOther_v1"), QString("Друга директория:"), QString("Other folder:"));
    setStr(TOOfficialMatCrossBibleWebSite_v1, QString("TOOfficialMatCrossBibleWebSite_v1"), QString("Официален сайт на MatCrossBible"), QString("Official MatCrossBible web site"));
    setStr(TOProxyTypeTT_v1, QString("TOProxyTypeTT_v1"), QString("Тип на Proxy (ако има)"), QString("Type of proxy (if any)"));
    setStr(TOProxyHostNameTT_v1, QString("TOProxyHostNameTT_v1"), QString("Пример: 192.168.1.100"), QString("Example: 192.168.1.100"));
    setStr(TOProxyPortTT_v1, QString("TOProxyPortTT_v1"), QString("Пример: 3128"), QString("Example: 3128"));
    setStr(TOMinimizeWindowToTray_v1, QString("TOMinimizeWindowToTray_v1"), QString("Минимизиране на прозореца в системния трей"), QString("Minimize window to system tray"));
    setStr(TOMinimizeWindowToTrayTT_v1, QString("TOMinimizeWindowToTrayTT_v1"), QString("Минимизира прозореца в системния трей при натискане на бутона за затваряне в заглавната лента на прозореца"), QString("Minimize window to system tray when the close button is pressed"));
    setStr(TOCreateDctCmtExampleFiles_v1, QString("TOCreateDctCmtExampleFiles_v1"), QString("Генериране на примерни файлове за речник и коментар"), QString("Generate example files for dictionary and commentaries"));
    setStr(TOCreateDctCmtExampleFilesDone_v1, QString("TOCreateDctCmtExampleFilesDone_v1"), QString("Файловете са в директория:"), QString("Files are located in:"));
  strSettings->endGroup();
}

void TrStrings::createNewReadMeFile()
{
  QString text(
    // Този текст ще го има само на английски:
    // За да преведете интерфейса на програмата на друг език, направете копие на някой от
    // съществуващите .tr файлове (например на English.tr), дайте му подходящо име, отворете го
    // с програма като Notepad или Notepad++ и преведете текста, като се стремите да спазвате
    // дължината на изреченията и да запазвате специалните знаци и тагове. 
    // Новият превод ще се появи в програмата при следващото й пускане и ще можете да го изберете
    // от настройките.
    //
    // Файлът трябва да бъде в UTF-8 формат!

    "In order to translate the interface of the App into another language, make a copy of one of\n"
    "the existing .tr files (for example English.tr), give it a proper name, open it in a file\n"
    "editing program such as Notepad or Notepad++ and translate the text. Make sure you keep the\n"
    "special symbols and tags and try to respect the length of the sentences.\n"
    "The new translation will appear inside the App after the next restart and can be selected\n"
    "from the settings.\n"
    "\n"
    "The file must be in UTF-8 format!\n"
    "\n"
    "\n"
    "Sample File Names: \n"
    "================== \n"
    "Abkhazian.tr \n"
    "Afan.tr \n"
    "Afar.tr \n"
    "Afrikaans.tr \n"
    "Akan.tr \n"
    "Albanian.tr \n"
    "Amharic.tr \n"
    "Arabic.tr \n"
    "Armenian.tr \n"
    "Assamese.tr \n"
    "Asu.tr \n"
    "Atsam.tr \n"
    "Aymara.tr \n"
    "Azerbaijani.tr \n"
    "Bambara.tr \n"
    "Bashkir.tr \n"
    "Basque.tr \n"
    "Bemba.tr \n"
    "Bena.tr \n"
    "Bengali.tr \n"
    "Bhutani.tr \n"
    "Bihari.tr \n"
    "Bislama.tr \n"
    "Blin.tr \n"
    "Bosnian.tr \n"
    "Breton.tr \n"
    "Bulgarian.tr \n"
    "Burmese.tr \n"
    "Byelorussian.tr \n"
    "Cambodian.tr \n"
    "Catalan.tr \n"
    "CentralMoroccoTamazight.tr \n"
    "Cherokee.tr \n"
    "Chewa.tr \n"
    "Chiga.tr \n"
    "Chinese.tr \n"
    "ChineseSimp.tr \n"
    "ChineseTrad.tr \n"
    "Colognian.tr \n"
    "Cornish.tr \n"
    "Corsican.tr \n"
    "Croatian.tr \n"
    "Czech.tr \n"
    "Danish.tr \n"
    "Divehi.tr \n"
    "Divehi.tr \n"
    "Dutch.tr \n"
    "Embu.tr \n"
    "English.tr \n"
    "Esperanto.tr \n"
    "Estonian.tr \n"
    "Ewe.tr \n"
    "Faroese.tr \n"
    "FijiLanguage.tr \n"
    "Filipino.tr \n"
    "Finnish.tr \n"
    "French.tr \n"
    "Frisian.tr \n"
    "Friulian.tr \n"
    "Fulah.tr \n"
    "Ga.tr \n"
    "Gaelic.tr \n"
    "Galician.tr \n"
    "Ganda.tr \n"
    "Geez.tr \n"
    "Georgian.tr \n"
    "German.tr \n"
    "Greek.tr \n"
    "Greenlandic.tr \n"
    "Guarani.tr \n"
    "Gujarati.tr \n"
    "Gusii.tr \n"
    "Hausa.tr \n"
    "Hawaiian.tr \n"
    "Hebrew.tr \n"
    "Hindi.tr \n"
    "Hungarian.tr \n"
    "Icelandic.tr \n"
    "Igbo.tr \n"
    "Indonesian.tr \n"
    "Interlingua.tr \n"
    "Interlingue.tr \n"
    "Inuktitut.tr \n"
    "Inupiak.tr \n"
    "Irish.tr \n"
    "Italian.tr \n"
    "Japanese.tr \n"
    "Javanese.tr \n"
    "Jju.tr \n"
    "Kabuverdianu.tr \n"
    "Kabyle.tr \n"
    "Kalenjin.tr \n"
    "Kamba.tr \n"
    "Kannada.tr \n"
    "Kashmiri.tr \n"
    "Kazakh.tr \n"
    "Kikuyu.tr \n"
    "Kinyarwanda.tr \n"
    "Kirghiz.tr \n"
    "Konkani.tr \n"
    "Korean.tr \n"
    "Koro.tr \n"
    "KoyraboroSenni.tr \n"
    "KoyraChiini.tr \n"
    "Kpelle.tr \n"
    "Kurdish.tr \n"
    "Kurundi.tr \n"
    "Langi.tr \n"
    "Laothian.tr \n"
    "Latin.tr \n"
    "Latvian.tr \n"
    "Lingala.tr \n"
    "Lithuanian.tr \n"
    "LowGerman.tr \n"
    "Luo.tr \n"
    "Luyia.tr \n"
    "Macedonian.tr \n"
    "Machame.tr \n"
    "Makonde.tr \n"
    "Malagasy.tr \n"
    "Malay.tr \n"
    "Malayalam.tr \n"
    "Maltese.tr \n"
    "Manx.tr \n"
    "Maori.tr \n"
    "Marathi.tr \n"
    "Masai.tr \n"
    "Meru.tr \n"
    "Moldavian.tr \n"
    "Mongolian.tr \n"
    "Morisyen.tr \n"
    "Nama.tr \n"
    "NauruLanguage.tr \n"
    "Nepali.tr \n"
    "NorthernSami.tr \n"
    "NorthernSotho.tr \n"
    "NorthNdebele.tr \n"
    "Norwegian.tr \n"
    "NorwegianBokmal.tr \n"
    "NorwegianNynorsk.tr \n"
    "Nyankole.tr \n"
    "Occitan.tr \n"
    "Oriya.tr \n"
    "Pashto.tr \n"
    "Persian.tr \n"
    "Polish.tr \n"
    "Portuguese.tr \n"
    "Punjabi.tr \n"
    "Quechua.tr \n"
    "RhaetoRomance.tr \n"
    "Romanian.tr \n"
    "Rombo.tr \n"
    "Russian.tr \n"
    "Rwa.tr \n"
    "Saho.tr \n"
    "Samburu.tr \n"
    "Samoan.tr \n"
    "Sangho.tr \n"
    "Sanskrit.tr \n"
    "Sena.tr \n"
    "Serbian.tr \n"
    "SerboCroatian.tr \n"
    "Sesotho.tr \n"
    "Setswana.tr \n"
    "Shambala.tr \n"
    "Shona.tr \n"
    "SichuanYi.tr \n"
    "Sidamo.tr \n"
    "Sindhi.tr \n"
    "Singhalese.tr \n"
    "Siswati.tr \n"
    "Slovak.tr \n"
    "Slovenian.tr \n"
    "Soga.tr \n"
    "Somali.tr \n"
    "SouthNdebele.tr \n"
    "Spanish.tr \n"
    "Sundanese.tr \n"
    "Swahili.tr \n"
    "Swedish.tr \n"
    "SwissGerman.tr \n"
    "Syriac.tr \n"
    "Tachelhit.tr \n"
    "Tagalog.tr \n"
    "Taita.tr \n"
    "Tajik.tr \n"
    "Tamil.tr \n"
    "Taroko.tr \n"
    "Tatar.tr \n"
    "Telugu.tr \n"
    "Teso.tr \n"
    "Thai.tr \n"
    "Tibetan.tr \n"
    "Tigre.tr \n"
    "Tigrinya.tr \n"
    "TongaLanguage.tr \n"
    "Tsonga.tr \n"
    "Turkish.tr \n"
    "Turkmen.tr \n"
    "Twi.tr \n"
    "Tyap.tr \n"
    "Uigur.tr \n"
    "Ukrainian.tr \n"
    "Urdu.tr \n"
    "Uzbek.tr \n"
    "Venda.tr \n"
    "Vietnamese.tr \n"
    "Volapuk.tr \n"
    "Vunjo.tr \n"
    "Walamo.tr \n"
    "Welsh.tr \n"
    "Wolof.tr \n"
    "Xhosa.tr \n"
    "Yiddish.tr \n"
    "Yoruba.tr \n"
    "Zhuang.tr \n"
    "Zulu.tr \n");

  // Създава файла и записва горния текст:
  QString fileName(QString("%1/ReadMe.txt").arg(trPath));
  if (!QFile::exists(fileName)) // Ако няма такъв файл.
  {
    QFile *file = new QFile(fileName);
    if (file->open(QFile::ReadWrite | QFile::Text | QIODevice::Truncate))
    {
      QTextStream out(file);
      out << text;
    }
    file->close();
    delete file;
  }
}
